function path = cartesianWaypoints( ...
        points,moveDurations,dwellDurations,sampleTime)
%CARTESIANWAYPOINTS Compose rest-to-rest Cartesian waypoint segments.
arguments
    points double
    moveDurations double
    dwellDurations double
    sampleTime double
end

waypointCount = size(points,2);
segmentCount = waypointCount-1;
if ~isnumeric(points) || ~isreal(points) || ...
        size(points,1) ~= 2 || waypointCount < 2 || ...
        any(~isfinite(points),"all") || ...
        ~isequal(size(moveDurations),[segmentCount 1]) || ...
        ~isequal(size(dwellDurations),[segmentCount 1]) || ...
        ~isreal(moveDurations) || ~isreal(dwellDurations) || ...
        any(~isfinite(moveDurations)) || ...
        any(~isfinite(dwellDurations)) || ...
        any(moveDurations <= 0) || any(dwellDurations < 0) || ...
        ~isPositiveScalar(sampleTime) || ...
        ~allOnGrid(moveDurations,sampleTime) || ...
        ~allOnGrid(dwellDurations,sampleTime)
    error("rrm:trajectory:InvalidWaypointPath", ...
        "Waypoint geometry and duration grid must be valid.");
end

path = struct( ...
    "time",0, ...
    "position",points(:,1), ...
    "velocity",zeros(2,1), ...
    "acceleration",zeros(2,1), ...
    "arrivalIndices",zeros(segmentCount,1), ...
    "dwellEndIndices",zeros(segmentCount,1));

for segmentIndex = 1:segmentCount
    moveDuration = moveDurations(segmentIndex);
    totalDuration = moveDuration+dwellDurations(segmentIndex);
    segment = rrm.trajectory.cartesianQuintic( ...
        points(:,segmentIndex),points(:,segmentIndex+1), ...
        moveDuration,sampleTime,totalDuration);
    previousCount = numel(path.time);
    path.arrivalIndices(segmentIndex) = previousCount+ ...
        round(moveDuration/sampleTime);
    path.dwellEndIndices(segmentIndex) = previousCount+ ...
        round(totalDuration/sampleTime);
    path.time = [path.time;path.time(end)+segment.time(2:end)];
    path.position = [path.position,segment.position(:,2:end)];
    path.velocity = [path.velocity,segment.velocity(:,2:end)];
    path.acceleration = [ ...
        path.acceleration,segment.acceleration(:,2:end)];
end
end

function valid = isPositiveScalar(value)
valid = isnumeric(value) && isreal(value) && isscalar(value) && ...
    isfinite(value) && value > 0;
end

function valid = allOnGrid(durations,sampleTime)
stepCounts = round(durations/sampleTime);
valid = all(abs(stepCounts*sampleTime-durations) <= ...
    100*eps(max(durations,1)));
end
