function reference = cartesianToJoint(robot,path,initialJoint)
%CARTESIANTOJOINT Convert a Cartesian path to a continuous joint reference.
arguments
    robot (1,1) struct
    path (1,1) struct
    initialJoint double
end

validateInputs(robot,path,initialJoint);
sampleCount = numel(path.time);
q = zeros(2,sampleCount);
previous = initialJoint;
for sample = 1:sampleCount
    [solutions,reachable] = rrm.kinematics.inverse( ...
        robot,path.position(:,sample));
    if ~reachable
        error("rrm:trajectory:UnreachableCartesianPoint", ...
            "Cartesian path sample %d is unreachable.",sample);
    end
    candidates = equivalentCandidates(solutions);
    withinLimits = all(candidates >= robot.jointLimits(:,1)-1e-12 & ...
        candidates <= robot.jointLimits(:,2)+1e-12,1);
    candidates = candidates(:,withinLimits);
    if isempty(candidates)
        error("rrm:trajectory:JointLimitViolation", ...
            "No inverse-kinematics branch satisfies the joint limits.");
    end
    distances = sum((candidates-previous).^2,1);
    [~,selected] = min(distances);
    q(:,sample) = candidates(:,selected);
    previous = q(:,sample);
end

dq = zeros(2,sampleCount);
ddq = zeros(2,sampleCount);
for sample = 1:sampleCount
    J = rrm.kinematics.jacobian(robot,q(:,sample));
    if rcond(J) <= 1e-8
        error("rrm:trajectory:SingularCartesianPath", ...
            "Cartesian path sample %d has a singular Jacobian.",sample);
    end
    dq(:,sample) = J\path.velocity(:,sample);
    Jdot = rrm.kinematics.jacobianDot( ...
        robot,q(:,sample),dq(:,sample));
    ddq(:,sample) = J\(path.acceleration(:,sample)- ...
        Jdot*dq(:,sample));
end

reference = struct( ...
    "time",path.time, ...
    "q",q, ...
    "dq",dq, ...
    "ddq",ddq, ...
    "cartesian",path);
end

function candidates = equivalentCandidates(solutions)
wrapOffsets = [-2*pi,0,2*pi];
candidates = zeros(2,18);
candidateIndex = 0;
for branch = 1:2
    for firstOffset = wrapOffsets
        for secondOffset = wrapOffsets
            candidateIndex = candidateIndex+1;
            candidates(:,candidateIndex) = solutions(:,branch)+ ...
                [firstOffset;secondOffset];
        end
    end
end
end

function validateInputs(robot,path,initialJoint)
requiredRobot = ["L1","L2","jointLimits"];
requiredPath = ["time","position","velocity","acceleration"];
if ~all(isfield(robot,requiredRobot)) || ...
        ~isequal(size(robot.jointLimits),[2 2]) || ...
        any(~isfinite(robot.jointLimits),"all") || ...
        any(robot.jointLimits(:,1) > robot.jointLimits(:,2)) || ...
        ~all(isfield(path,requiredPath)) || ...
        ~isnumeric(initialJoint) || ~isreal(initialJoint) || ...
        ~isequal(size(initialJoint),[2 1]) || ...
        any(~isfinite(initialJoint))
    error("rrm:trajectory:InvalidCartesianPath", ...
        "Robot, Cartesian path, and initial joint must be valid.");
end
sampleCount = numel(path.time);
validArrays = isnumeric(path.time) && isreal(path.time) && ...
    isequal(size(path.time),[sampleCount 1]) && ...
    isnumeric(path.position) && isreal(path.position) && ...
    isequal(size(path.position),[2 sampleCount]) && ...
    isnumeric(path.velocity) && isreal(path.velocity) && ...
    isequal(size(path.velocity),[2 sampleCount]) && ...
    isnumeric(path.acceleration) && isreal(path.acceleration) && ...
    isequal(size(path.acceleration),[2 sampleCount]) && ...
    all(isfinite(path.time)) && all(isfinite(path.position),"all") && ...
    all(isfinite(path.velocity),"all") && ...
    all(isfinite(path.acceleration),"all") && ...
    sampleCount >= 2 && all(diff(path.time) > 0);
if ~validArrays
    error("rrm:trajectory:InvalidCartesianPath", ...
        "Cartesian path arrays must be finite and dimensionally consistent.");
end
end
