function path = cartesianQuintic( ...
        p0,pf,moveDuration,sampleTime,totalDuration)
%CARTESIANQUINTIC Generate a rest-to-rest straight Cartesian segment.
arguments
    p0 double
    pf double
    moveDuration double
    sampleTime double
    totalDuration double = moveDuration
end

if ~isVector(p0) || ~isVector(pf) || ...
        ~isPositiveScalar(moveDuration) || ...
        ~isPositiveScalar(sampleTime) || ...
        ~isPositiveScalar(totalDuration) || totalDuration < moveDuration || ...
        ~isOnGrid(moveDuration,sampleTime) || ...
        ~isOnGrid(totalDuration,sampleTime)
    error("rrm:trajectory:InvalidCartesianPath", ...
        "Cartesian endpoints and duration grid must be valid.");
end

stepCount = round(totalDuration/sampleTime);
time = (0:stepCount).'*sampleTime;
normalizedTime = min(time/moveDuration,1);
s = 10*normalizedTime.^3-15*normalizedTime.^4+ ...
    6*normalizedTime.^5;
ds = (30*normalizedTime.^2-60*normalizedTime.^3+ ...
    30*normalizedTime.^4)/moveDuration;
dds = (60*normalizedTime-180*normalizedTime.^2+ ...
    120*normalizedTime.^3)/moveDuration^2;

delta = pf-p0;
path = struct( ...
    "time",time, ...
    "position",p0+delta*s.', ...
    "velocity",delta*ds.', ...
    "acceleration",delta*dds.');
end

function valid = isVector(value)
valid = isnumeric(value) && isreal(value) && ...
    isequal(size(value),[2 1]) && all(isfinite(value));
end

function valid = isPositiveScalar(value)
valid = isnumeric(value) && isreal(value) && isscalar(value) && ...
    isfinite(value) && value > 0;
end

function valid = isOnGrid(duration,sampleTime)
stepCount = round(duration/sampleTime);
valid = abs(stepCount*sampleTime-duration) <= ...
    100*eps(max(duration,1));
end
