function task = makePickAndPlaceTask(robot,sampleTime)
%MAKEPICKANDPLACETASK Create the prescribed Cartesian waypoint task.
arguments
    robot (1,1) struct
    sampleTime (1,1) double {mustBeFinite,mustBeReal,mustBePositive}
end

waypointNames = ["start";"pickup";"safe";"place"];
waypoints = [0.55 0.45 0.45 0.22; ...
    0.12 -0.02 0.32 0.48];
moveDurations = [1.4;1.2;1.5];
dwellDurations = [0.4;0;0.8];
path = rrm.trajectory.cartesianWaypoints( ...
    waypoints,moveDurations,dwellDurations,sampleTime);
[solutions,reachable] = rrm.kinematics.inverse( ...
    robot,path.position(:,1));
if ~reachable
    error("rrm:trajectory:UnreachableCartesianPoint", ...
        "The prescribed pick-and-place start point is unreachable.");
end
initialJoint = solutions(:,1);
reference = rrm.trajectory.cartesianToJoint( ...
    robot,path,initialJoint);
pickupEvaluationIndex = path.dwellEndIndices(1);
placeEvaluationIndex = path.dwellEndIndices(3);

task = struct( ...
    "name","pick-transfer-place", ...
    "waypointNames",waypointNames, ...
    "waypoints",waypoints, ...
    "moveDurations",moveDurations, ...
    "dwellDurations",dwellDurations, ...
    "initialJoint",initialJoint, ...
    "path",path, ...
    "reference",reference, ...
    "pickupEvaluationIndex",pickupEvaluationIndex, ...
    "placeEvaluationIndex",placeEvaluationIndex, ...
    "evaluationIndices",struct( ...
        "pickup",pickupEvaluationIndex, ...
        "place",placeEvaluationIndex));
end
