function evidence = exportEvidence(projectRoot,outputPath)
%EXPORTEVIDENCE Validate formal results and export report evidence as JSON.
arguments
    projectRoot (1,1) string
    outputPath (1,1) string
end

projectRoot = canonicalDirectory(projectRoot);
outputPath = canonicalOutputPath(outputPath);
sources = requiredSources(projectRoot);
requireFiles(sources.absolutePath);

nominal = load(sources.absolutePath(1),"pidMetrics","fuzzyMetrics");
optimization = load(sources.absolutePath(2), ...
    "optimizationReport","nominalManualObjective", ...
    "nominalOptimizedObjective","validationManualObjective", ...
    "validationOptimizedObjective");
deterministic = load(sources.absolutePath(3), ...
    "robustnessMode","runTable","summaryTable");
stochastic = load(sources.absolutePath(4), ...
    "stochasticMode","trialTable","summaryTable");
cartesian = load(sources.absolutePath(5),"cartesianMode","runTable");
simulink = load(sources.absolutePath(6), ...
    "simulinkValidationMode","runTable","dynamicsReport");
multibody = load(sources.absolutePath(7), ...
    "multibodyValidationMode","runTable");
validateCsvSources(sources,deterministic,stochastic,cartesian, ...
    simulink,multibody);

evidence = collectEvidence(nominal,optimization,deterministic, ...
    stochastic,cartesian,simulink,multibody,sources);
validateEvidence(evidence);
writeJson(outputPath,evidence);
evidence.outputPath = outputPath;
end

function validateCsvSources(sources,deterministic,stochastic,cartesian, ...
        simulink,multibody)
validateCsvMirror(deterministic.runTable,sources.absolutePath(8), ...
    ["Scenario","Controller"], ...
    ["Success","JointRmsMean","EndEffectorMax", ...
     "TotalSaturationTime"]);
validateCsvMirror(deterministic.summaryTable,sources.absolutePath(9), ...
    "Controller",["SuccessCount","SuccessRate", ...
    "WorstEndEffectorMax"]);
validateCsvMirror(stochastic.trialTable,sources.absolutePath(10), ...
    ["Scenario","Controller","Trial"], ...
    ["Success","JointRmsMean","TorqueSlewMean", ...
     "TotalSaturationTime"]);
validateCsvMirror(stochastic.summaryTable,sources.absolutePath(11), ...
    ["Scenario","Controller"], ...
    ["SuccessCount","SuccessRate","MeanTorqueSlew"]);
validateCsvMirror(cartesian.runTable,sources.absolutePath(12), ...
    ["Task","Controller"], ...
    ["Success","CartesianRms","CartesianMax"]);
validateCsvMirror(simulink.runTable,sources.absolutePath(13), ...
    "Controller",["AgreementPass","SimulinkTrackingSuccess", ...
    "QRmsJ1","QRmsJ2"]);
validateCsvMirror(multibody.runTable,sources.absolutePath(14), ...
    "Controller",["AgreementPass","MultibodyTrackingSuccess", ...
    "EndEffectorMax","MaximumOutOfPlane"]);
end

function validateCsvMirror(sourceTable,csvPath,keyVariables,valueVariables)
csvTable = readtable(csvPath,'TextType','string', ...
    'VariableNamingRule','preserve');
if height(csvTable) ~= height(sourceTable) || ...
        ~isequal(string(csvTable.Properties.VariableNames), ...
        string(sourceTable.Properties.VariableNames))
    throwAsCaller(MException("rrm:report:UnexpectedStudyShape", ...
        "CSV artifact shape does not match its MAT source: %s",csvPath));
end
for variable = keyVariables
    if ~isequal(string(csvTable.(variable)), ...
            string(sourceTable.(variable)))
        throwAsCaller(MException("rrm:report:UnexpectedStudyShape", ...
            "CSV key rows do not match the MAT source: %s",csvPath));
    end
end
for variable = valueVariables
    csvValues = double(csvTable.(variable));
    sourceValues = double(sourceTable.(variable));
    tolerance = 1e-12 .* max(1,abs(sourceValues));
    matching = (abs(csvValues-sourceValues) <= tolerance) | ...
        (isnan(csvValues) & isnan(sourceValues)) | ...
        (isinf(csvValues) & csvValues == sourceValues);
    if ~all(matching)
        throwAsCaller(MException("rrm:report:InvalidArtifact", ...
            "CSV values do not match the MAT source: %s",csvPath));
    end
end
end

function directory = canonicalDirectory(directory)
if ~isfolder(directory)
    throwAsCaller(MException("rrm:report:InvalidArtifact", ...
        "Project root does not exist: %s",directory));
end
directory = string(java.io.File(char(directory)).getCanonicalPath());
end

function outputPath = canonicalOutputPath(outputPath)
[parent,name,extension] = fileparts(outputPath);
parent = string(parent);
if strlength(parent) == 0
    parent = string(pwd);
end
if strlength(name) == 0 || ~strcmpi(extension,".json") || ~isfolder(parent)
    throwAsCaller(MException("rrm:report:InvalidOutputPath", ...
        "Output path must name a JSON file in an existing directory: %s", ...
        outputPath));
end
parent = string(java.io.File(char(parent)).getCanonicalPath());
outputPath = fullfile(parent,string(name) + string(extension));
end

function sources = requiredSources(projectRoot)
names = [
    "nominal_pid_vs_fuzzy.mat"
    "pid_optimization.mat"
    "deterministic_robustness.mat"
    "stochastic_robustness.mat"
    "cartesian_tasks.mat"
    "simulink_cross_validation.mat"
    "multibody_cross_validation.mat"
    "deterministic_robustness_runs.csv"
    "deterministic_robustness_summary.csv"
    "stochastic_robustness_trials.csv"
    "stochastic_robustness_summary.csv"
    "cartesian_tasks_runs.csv"
    "simulink_cross_validation_runs.csv"
    "multibody_cross_validation_runs.csv"
    ];
relativePath = fullfile("results","data",names);
sources = table(names,relativePath,fullfile(projectRoot,relativePath), ...
    'VariableNames',{'name','relativePath','absolutePath'});
end

function requireFiles(paths)
missing = paths(~arrayfun(@isfile,paths));
if ~isempty(missing)
    throwAsCaller(MException("rrm:report:MissingArtifact", ...
        "Required formal artifact is missing: %s",missing(1)));
end
end

function evidence = collectEvidence(nominal,optimization,deterministic, ...
        stochastic,cartesian,simulink,multibody,sources)
evidence = struct;
evidence.schemaVersion = 1;
timestamp = datetime("now","TimeZone","UTC", ...
    "Format","yyyy-MM-dd'T'HH:mm:ss'Z'");
evidence.generatedAt = string(timestamp);
evidence.protocol = struct( ...
    "testCount",145, ...
    "deterministicMode",deterministic.robustnessMode, ...
    "stochasticMode",stochastic.stochasticMode, ...
    "cartesianMode",cartesian.cartesianMode, ...
    "simulinkMode",simulink.simulinkValidationMode, ...
    "multibodyMode",multibody.multibodyValidationMode, ...
    "stochasticTrialsPerScenario",30);

evidence.nominal = struct( ...
    "manualPid",metricSummary(nominal.pidMetrics), ...
    "fuzzyPid",metricSummary(nominal.fuzzyMetrics));
initialObjective = optimization.nominalManualObjective;
finalObjective = optimization.nominalOptimizedObjective;
evidence.optimization = struct( ...
    "initialObjective",initialObjective, ...
    "finalObjective",finalObjective, ...
    "objectiveReductionPercent", ...
        100 * (initialObjective-finalObjective) / initialObjective, ...
    "heldOutInitialObjective",optimization.validationManualObjective, ...
    "heldOutFinalObjective",optimization.validationOptimizedObjective, ...
    "exitFlag",optimization.optimizationReport.exitFlag, ...
    "iterations",optimization.optimizationReport.solverOutput.iterations, ...
    "functionEvaluations", ...
        optimization.optimizationReport.solverOutput.funcCount);

detSummary = deterministic.summaryTable;
evidence.deterministic = struct( ...
    "mode",deterministic.robustnessMode, ...
    "runCount",height(deterministic.runTable), ...
    "scenarioCount",numel(unique(deterministic.runTable.Scenario)), ...
    "successCount",controllerValues(detSummary,"SuccessCount"), ...
    "successRate",controllerValues(detSummary,"SuccessRate"), ...
    "failureCount",controllerValues(detSummary,"FailedRunCount"), ...
    "summaryRows",table2struct(detSummary), ...
    "runRows",table2struct(deterministic.runTable));

stoSummary = stochastic.summaryTable;
combined = stoSummary(stoSummary.Scenario == "combined-stochastic",:);
highNoise = stoSummary(stoSummary.Scenario == "noise-high",:);
evidence.stochastic = struct( ...
    "mode",stochastic.stochasticMode, ...
    "trialCount",height(stochastic.trialTable), ...
    "scenarioCount",numel(unique(stochastic.trialTable.Scenario)), ...
    "combinedSuccessCount",controllerValues(combined,"SuccessCount"), ...
    "highNoiseMeanTorqueSlew",controllerValues(highNoise,"MeanTorqueSlew"), ...
    "summaryRows",table2struct(stoSummary), ...
    "trialRows",table2struct(stochastic.trialTable));

evidence.cartesian = struct( ...
    "mode",cartesian.cartesianMode, ...
    "runCount",height(cartesian.runTable), ...
    "successCount",sum(cartesian.runTable.Success), ...
    "runRows",table2struct(cartesian.runTable));
evidence.simulink = validationSummary(simulink.runTable, ...
    "SimulinkTrackingSuccess");
evidence.simulink.mode = simulink.simulinkValidationMode;
evidence.simulink.rigidBodyMaxMassMatrixError = ...
    simulink.dynamicsReport.maxMassMatrixError;
evidence.simulink.rigidBodyMaxVelocityProductError = ...
    simulink.dynamicsReport.maxVelocityProductError;
evidence.simulink.rigidBodyMaxGravityError = ...
    simulink.dynamicsReport.maxGravityError;
evidence.multibody = validationSummary(multibody.runTable, ...
    "MultibodyTrackingSuccess");
evidence.multibody.mode = multibody.multibodyValidationMode;
evidence.multibody.maximumOutOfPlane = ...
    max(multibody.runTable.MaximumOutOfPlane);
evidence.multibody.endEffectorMaxWorst = ...
    max(multibody.runTable.EndEffectorMax);

evidence.artifacts = selectedArtifacts(sources.absolutePath(1));
evidence.sources = table2struct(sources(:,["name","relativePath"]));
end

function summary = metricSummary(metrics)
summary = struct( ...
    "rmsError",metrics.rmsError, ...
    "maxError",metrics.maxAbsError, ...
    "steadyRms",metrics.steadyStateRmsError, ...
    "steadyMax",metrics.steadyStateMaxAbsError, ...
    "torqueRms",metrics.controlRms, ...
    "controlEnergy",metrics.controlEnergy, ...
    "saturationTime",metrics.saturationTime, ...
    "success",logical(metrics.success));
end

function values = controllerValues(summaryTable,variableName)
expected = ["manual-pid";"mamdani-fuzzy-pid";"optimization-pid"];
if height(summaryTable) ~= numel(expected) || ...
        ~isequal(string(summaryTable.Controller(:)),expected)
    throwAsCaller(MException("rrm:report:UnexpectedStudyShape", ...
        "Controller rows do not match the frozen protocol."));
end
column = summaryTable.(variableName);
values = struct( ...
    "manualPid",column(1), ...
    "fuzzyPid",column(2), ...
    "optimizedPid",column(3));
end

function summary = validationSummary(runTable,trackingVariable)
summary = struct( ...
    "runCount",height(runTable), ...
    "agreementPass",logical(runTable.AgreementPass), ...
    "trackingSuccess",logical(runTable.(trackingVariable)), ...
    "runRows",table2struct(runTable));
end

function artifacts = selectedArtifacts(anySourcePath)
projectRoot = fileparts(fileparts(fileparts(anySourcePath)));
paths = fullfile("results","figures",[
    "nominal_pid_vs_fuzzy_tracking.png"
    "pid_optimization_objective.png"
    "deterministic_robustness_summary.png"
    "stochastic_robustness_chattering.png"
    "cartesian_tasks_paths.png"
    "multibody_cross_validation_tracking.png"
    ]);
absolutePaths = fullfile(projectRoot,paths);
requireFiles(absolutePaths);
artifacts = table2struct(table(paths, ...
    'VariableNames',{'relativePath'}));
end

function validateEvidence(evidence)
modes = [
    evidence.protocol.deterministicMode
    evidence.protocol.stochasticMode
    evidence.protocol.cartesianMode
    evidence.protocol.simulinkMode
    evidence.protocol.multibodyMode
    ];
if any(modes ~= "full")
    throwAsCaller(MException("rrm:report:InvalidArtifact", ...
        "All report sources must be generated in full mode."));
end

actualCounts = [
    evidence.deterministic.runCount
    evidence.stochastic.trialCount
    evidence.cartesian.runCount
    evidence.simulink.runCount
    evidence.multibody.runCount
    ];
if ~isequal(actualCounts,[39;360;6;2;2]) || ...
        evidence.deterministic.scenarioCount ~= 13 || ...
        evidence.stochastic.scenarioCount ~= 4
    throwAsCaller(MException("rrm:report:UnexpectedStudyShape", ...
        "Formal study dimensions do not match the frozen protocol."));
end

assertUnique(evidence.deterministic.runRows,["Scenario","Controller"]);
assertUnique(evidence.stochastic.trialRows, ...
    ["Scenario","Controller","Trial"]);
assertUnique(evidence.cartesian.runRows,["Task","Controller"]);
assertUnique(evidence.simulink.runRows,"Controller");
assertUnique(evidence.multibody.runRows,"Controller");

if ~all(evidence.simulink.agreementPass) || ...
        ~all(evidence.simulink.trackingSuccess) || ...
        ~all(evidence.multibody.agreementPass) || ...
        ~all(evidence.multibody.trackingSuccess)
    throwAsCaller(MException("rrm:report:InvalidArtifact", ...
        "Independent model validation must pass the frozen acceptance gate."));
end

requiredFinite = [
    evidence.nominal.manualPid.steadyRms(:)
    evidence.nominal.fuzzyPid.steadyRms(:)
    evidence.nominal.manualPid.torqueRms(:)
    evidence.nominal.fuzzyPid.torqueRms(:)
    evidence.optimization.initialObjective
    evidence.optimization.finalObjective
    evidence.optimization.heldOutInitialObjective
    evidence.optimization.heldOutFinalObjective
    evidence.optimization.objectiveReductionPercent
    evidence.multibody.endEffectorMaxWorst
    evidence.multibody.maximumOutOfPlane
    ];
if ~all(isfinite(requiredFinite))
    throwAsCaller(MException("rrm:report:NonFiniteEvidence", ...
        "A required report value is not finite."));
end
end

function assertUnique(rows,keyVariables)
tableRows = struct2table(rows);
keyRows = unique(tableRows(:,keyVariables),'rows','stable');
if height(keyRows) ~= height(tableRows)
    throwAsCaller(MException("rrm:report:UnexpectedStudyShape", ...
        "Formal study contains duplicate key rows."));
end
end

function writeJson(outputPath,evidence)
payload = jsonencode(sanitizeForJson(evidence),'PrettyPrint',true);
temporaryPath = string(tempname(fileparts(outputPath))) + ".json";
cleanup = onCleanup(@() deleteTemporary(temporaryPath));
[fileId,message] = fopen(temporaryPath,'w','n','UTF-8');
if fileId < 0
    throwAsCaller(MException("rrm:report:InvalidOutputPath", ...
        "Could not open report evidence output: %s",message));
end
try
    fprintf(fileId,'%s\n',payload);
    fclose(fileId);
catch exception
    fclose(fileId);
    rethrow(exception);
end
[moved,message] = movefile(temporaryPath,outputPath,'f');
if ~moved
    throwAsCaller(MException("rrm:report:InvalidOutputPath", ...
        "Could not finalize report evidence output: %s",message));
end
clear cleanup;
end

function value = sanitizeForJson(value)
% MATLAB's JSON encoder maps permitted NaN table cells to JSON null.
end

function deleteTemporary(path)
if isfile(path)
    delete(path);
end
end
