classdef TestEvaluateStochasticRun < matlab.unittest.TestCase
    methods (Test)
        function trackingVarianceUsesTruePlantError(testCase)
            result = syntheticResult();
            metrics = rrm.robustness.evaluateStochasticRun( ...
                result,rrm.config.makeRobot("baseline"), ...
                generousCriteria(),scenario());
            expected = var(result.qReference-result.q,0,2);
            testCase.verifyEqual(metrics.trackingErrorVariance, expected, ...
                "AbsTol",1e-12);
            testCase.verifyEqual(metrics.robustness.common.rmsError, ...
                sqrt(mean((result.qReference-result.q).^2,2)), ...
                "AbsTol",1e-12);
        end

        function torqueSlewMatchesHandCalculation(testCase)
            result = syntheticResult();
            metrics = rrm.robustness.evaluateStochasticRun( ...
                result,rrm.config.makeRobot("baseline"), ...
                generousCriteria(),scenario());
            expected = sqrt(mean((diff(result.tau,1,2)/0.1).^2,2));
            testCase.verifyEqual(metrics.torqueSlewRms, expected, ...
                "AbsTol",1e-12);
            testCase.verifyEqual(metrics.torqueSlewMean, mean(expected), ...
                "AbsTol",1e-12);
        end

        function invalidTimeOrInsufficientSamplesAreRejected(testCase)
            robot = rrm.config.makeRobot("baseline");
            criteria = generousCriteria();
            currentScenario = scenario();
            duplicateTime = syntheticResult();
            duplicateTime.time(3) = duplicateTime.time(2);
            testCase.verifyError(@() ...
                rrm.robustness.evaluateStochasticRun( ...
                duplicateTime,robot,criteria,currentScenario), ...
                "rrm:robustness:InvalidStochasticResult");

            oneSample = syntheticResult();
            oneSample.q(:,2:end) = NaN;
            oneSample.tau(:,2:end) = NaN;
            testCase.verifyError(@() ...
                rrm.robustness.evaluateStochasticRun( ...
                oneSample,robot,criteria,currentScenario), ...
                "rrm:robustness:InvalidStochasticResult");
        end
    end
end

function result = syntheticResult()
result = struct( ...
    "time",(0:0.1:0.3).', ...
    "q",[0 1 2 3;0 2 0 2], ...
    "qReference",zeros(2,4), ...
    "tau",[0 1 3 6;0 -2 -2 1], ...
    "saturated",false(2,4), ...
    "status","completed");
end

function criteria = generousCriteria()
criteria = struct( ...
    "steadyStateWindow",0.1, ...
    "steadyStateRmsError",[10;10], ...
    "steadyStateMaxAbsError",[10;10]);
end

function value = scenario()
value = struct( ...
    "disturbanceWindow",[NaN;NaN], ...
    "recoveryBand",deg2rad(2), ...
    "recoveryDwell",0.1);
end
