classdef TestRunStochasticStudy < matlab.unittest.TestCase
    methods (Test)
        function createsEveryPairedTrialAndRepresentativeRun(testCase)
            [definitions, scenarios, reference, criteria] = fixtures();
            study = rrm.robustness.runStochasticStudy( ...
                definitions,scenarios,reference,criteria);

            testCase.verifyEqual(height(study.table), 8);
            keys = study.table.Scenario + "|" + study.table.Controller + ...
                "|" + string(study.table.Trial) + "|" + ...
                string(study.table.Seed);
            testCase.verifyEqual(numel(unique(keys)), 8);
            testCase.verifyEqual(numel(study.representativeRuns), 4);
            testCase.verifyEqual([study.representativeRuns.trial], ...
                ones(1,4));
            testCase.verifyTrue(all(strlength(study.table.Status) > 0));
        end

        function controllersShareIdenticalNoiseWithinScenarioSeed(testCase)
            [definitions, scenarios, reference, criteria] = fixtures();
            study = rrm.robustness.runStochasticStudy( ...
                definitions,scenarios,reference,criteria);

            pairKeys = unique(study.table.Scenario + "|" + ...
                string(study.table.Seed),"stable");
            for key = pairKeys.'
                selected = study.table.Scenario + "|" + ...
                    string(study.table.Seed) == key;
                testCase.verifyEqual( ...
                    numel(unique(study.table.PositionNoiseRms(selected))),1);
                testCase.verifyEqual( ...
                    numel(unique(study.table.VelocityNoiseRms(selected))),1);
            end

            for scenarioName = unique(study.table.Scenario,"stable").'
                representatives = study.representativeRuns( ...
                    [study.representativeRuns.scenarioName] == scenarioName);
                testCase.verifyEqual( ...
                    representatives(1).result.measurementNoise, ...
                    representatives(2).result.measurementNoise);
            end
        end

        function invalidDefinitionsScenariosAndSeedsAreRejected(testCase)
            [definitions, scenarios, reference, criteria] = fixtures();
            duplicateDefinitions = [definitions(1) definitions(1)];
            testCase.verifyError(@() ...
                rrm.robustness.runStochasticStudy(duplicateDefinitions, ...
                scenarios,reference,criteria), ...
                "rrm:robustness:InvalidStochasticStudy");

            duplicateScenarios = [scenarios(1) scenarios(1)];
            testCase.verifyError(@() ...
                rrm.robustness.runStochasticStudy(definitions, ...
                duplicateScenarios,reference,criteria), ...
                "rrm:robustness:InvalidStochasticStudy");

            scenarios(1).seeds = [42001 42001];
            testCase.verifyError(@() ...
                rrm.robustness.runStochasticStudy(definitions, ...
                scenarios,reference,criteria), ...
                "rrm:robustness:InvalidStochasticStudy");
            scenarios(1).seeds = [];
            testCase.verifyError(@() ...
                rrm.robustness.runStochasticStudy(definitions, ...
                scenarios,reference,criteria), ...
                "rrm:robustness:InvalidStochasticStudy");
        end
    end
end

function [definitions, scenarios, reference, criteria] = fixtures()
options = rrm.config.makeSimulationOptions();
reference = rrm.trajectory.quintic( ...
    [0;0],deg2rad([5;8]),0.08,options.sampleTime,0.12);
scenarios = rrm.robustness.makeStochasticScenarios( ...
    reference,options,"smoke");
robot = rrm.config.makeRobot("baseline");
definitions(1) = struct("name","manual-pid", ...
    "controller",rrm.config.makePidController(robot));
definitions(2) = struct("name","optimization-pid", ...
    "controller",rrm.config.makeOptimizedPidController(robot));
criteria = options.successCriteria;
end
