classdef TestEvaluate < matlab.unittest.TestCase
    methods (Test)
        function calculatesKnownMetrics(testCase)
            result = struct( ...
                "time", [0; 1; 2], ...
                "q", [0 1 2; 0 0 0], ...
                "qReference", [0 2 2; 0 1 0], ...
                "tau", [1 1 1; 2 2 2], ...
                "saturated", false(2,3), ...
                "status", "completed");
            criteria = struct( ...
                "steadyStateWindow", 2, ...
                "steadyStateRmsError", [2;2], ...
                "steadyStateMaxAbsError", [2;2]);

            metrics = rrm.metrics.evaluate(result, criteria);

            testCase.verifyEqual( ...
                metrics.rmsError, sqrt([1/3; 1/3]), AbsTol=1e-12);
            testCase.verifyEqual(metrics.maxAbsError, [1;1], AbsTol=1e-12);
            testCase.verifyEqual(metrics.controlRms, [1;2], AbsTol=1e-12);
            testCase.verifyEqual(metrics.controlEnergy, 10, AbsTol=1e-12);
            testCase.verifyEqual(metrics.saturationTime, [0;0], AbsTol=1e-12);
            testCase.verifyTrue(metrics.success);
        end

        function failedSimulationCannotBeSuccessful(testCase)
            result = struct( ...
                "time", [0; 1], ...
                "q", zeros(2), ...
                "qReference", zeros(2), ...
                "tau", zeros(2), ...
                "saturated", false(2), ...
                "status", "joint-limit-violation");
            criteria = struct( ...
                "steadyStateWindow", 1, ...
                "steadyStateRmsError", [1;1], ...
                "steadyStateMaxAbsError", [1;1]);

            metrics = rrm.metrics.evaluate(result, criteria);

            testCase.verifyFalse(metrics.success);
        end
    end
end
