function modelName = buildCrossValidationModel(modelPath)
%BUILDCROSSVALIDATIONMODEL Build the Multibody validation model.
arguments
    modelPath (1,1) string
end

validateCapability();
modelPath = resolveModelPath(modelPath);
[~,name] = fileparts(modelPath);
modelName = string(name);
sourcePath = fullfile(projectRoot(),"models", ...
    "rrm_pid_cross_validation.slx");
if ~isfile(sourcePath)
    error("rrm:multibody:MissingSourceModel", ...
        "The verified Phase 6A source model is required.");
end

closeIfLoaded(modelName);
if isfile(modelPath)
    delete(modelPath);
end

sourceName = "rrm_pid_cross_validation";
sourceWasLoaded = bdIsLoaded(sourceName);
load_system(sourcePath);
sourceCleanup = onCleanup(@() closeSource(sourceName,sourceWasLoaded));
new_system(modelName);
try
set_param(modelName, ...
    "SolverType","Fixed-step", ...
    "Solver","ode4", ...
    "FixedStep","0.001", ...
    "StopTime","rrmStopTime", ...
    "SignalLogging","on", ...
    "ReturnWorkspaceOutputs","on");

add_block(sourceName + "/Reference",modelName + "/Reference", ...
    "Position",[30 80 230 280]);
add_block(sourceName + "/PID Controller", ...
    modelName + "/PID Controller", ...
    "Position",[350 40 650 320]);
add_block("simulink/Ports & Subsystems/Subsystem", ...
    modelName + "/Multibody Plant", ...
    "Position",[790 40 1070 320]);
add_block("simulink/Ports & Subsystems/Subsystem", ...
    modelName + "/Logging", ...
    "Position",[1200 70 1420 290]);
buildPhysicalPlant(modelName + "/Multibody Plant");
buildLogging(modelName + "/Logging");
connectTopLevel(modelName);
assignDefaults(modelName);
annotation = Simulink.Annotation(modelName, ...
    "Phase 6B torque-driven Simscape Multibody validation" + newline + ...
    "q [rad], dq [rad/s], tau [N m], end-effector position [m]");
annotation.Position = [410 370 1010 420];
save_system(modelName,modelPath);
catch exception
    closeIfLoaded(modelName);
    rethrow(exception);
end
clear sourceCleanup
end

function validateCapability()
if isempty(which("smnew")) || isempty(which("sm_lib")) || ...
        ~license("test","SimMechanics")
    error("rrm:multibody:MissingMultibody", ...
        "Simscape Multibody must be installed and licensed.");
end
end

function modelPath = resolveModelPath(modelPath)
if ~java.io.File(char(modelPath)).isAbsolute()
    modelPath = fullfile(projectRoot(),modelPath);
end
[parent,name,extension] = fileparts(modelPath);
if ~strcmpi(extension,".slx") || strlength(name) == 0 || ...
        ~isvarname(name)
    error("rrm:multibody:InvalidModelPath", ...
        "Model path must name a valid .slx file.");
end
if strlength(parent) == 0
    parent = ".";
end
if ~isfolder(parent)
    [created,message] = mkdir(parent);
    if ~created
        error("rrm:multibody:InvalidModelPath", ...
            "Unable to create model directory: %s",message);
    end
end
parent = string(java.io.File(char(parent)).getCanonicalPath());
modelPath = fullfile(parent,name + extension);
end

function root = projectRoot()
functionPath = mfilename("fullpath");
root = string(fileparts(fileparts(fileparts(functionPath))));
end

function assignDefaults(modelName)
robot = rrm.config.makeRobot("baseline");
controller = rrm.config.makePidController(robot);
sampleTime = 0.001;
reference = rrm.trajectory.quintic( ...
    [0;0],deg2rad([5;8]),0.02,sampleTime,0.03);
workspace = get_param(modelName,"ModelWorkspace");
assignin(workspace,"rrmSampleTime",sampleTime);
assignin(workspace,"rrmStopTime",reference.time(end));
assignin(workspace,"rrmQReferenceSignal", ...
    timeseries(reference.q.',reference.time));
assignin(workspace,"rrmDqReferenceSignal", ...
    timeseries(reference.dq.',reference.time));
assignin(workspace,"rrmKp",controller.Kp);
assignin(workspace,"rrmKi",controller.Ki);
assignin(workspace,"rrmKd",controller.Kd);
assignin(workspace,"rrmDerivativeAlpha", ...
    exp(-2*pi*controller.derivativeFilterHz*sampleTime));
assignin(workspace,"rrmAntiWindupGain",controller.antiWindupGain);
assignin(workspace,"rrmTorqueLimits",robot.torqueLimits);
assignin(workspace,"rrmInitialQ",reference.q(:,1));
assignin(workspace,"rrmInitialDq",zeros(2,1));
assignin(workspace,"rrmGravity",robot.gravity);
assignin(workspace,"rrmMbLinkLength",[robot.L1;robot.L2]);
assignin(workspace,"rrmMbLinkMass",[robot.m1;robot.m2]);
assignin(workspace,"rrmMbLinkInertia",robot.inertia);
assignin(workspace,"rrmMbPayload",robot.payload);
assignin(workspace,"rrmMbDamping",robot.viscousFriction);
assignin(workspace,"rrmMbWidth",0.06);
transverse = max(1e-6,0.01*robot.inertia);
assignin(workspace,"rrmMbMoments", ...
    [transverse robot.inertia robot.inertia]);
end

function buildPhysicalPlant(path)
Simulink.SubSystem.deleteContents(path);
add_block("simulink/Ports & Subsystems/In1",path + "/tau", ...
    "Port","1","Position",[20 40 50 60]);
add_block("simulink/Signal Routing/Demux",path + "/Torque Split", ...
    "Outputs","2","Position",[80 25 85 100]);

for joint = 1:2
    y = 25 + (joint-1)*70;
    add_block(libraryBlock("nesl_utility","Simulink-PS Converter"), ...
        path + "/Torque " + joint, ...
        "Unit","N*m","Position",[125 y 175 y+30]);
    add_block(libraryBlock("nesl_utility","PS-Simulink Converter"), ...
        path + "/Position " + joint, ...
        "Unit","rad","Position",[785 y 835 y+30]);
    add_block(libraryBlock("nesl_utility","PS-Simulink Converter"), ...
        path + "/Velocity " + joint, ...
        "Unit","rad/s","Position",[785 y+35 835 y+65]);
    jointPath = path + "/Revolute Joint " + joint;
    add_block(libraryBlock("sm_lib","Revolute Joint"),jointPath, ...
        "Position",[300 y 360 y+65]);
    set_param(jointPath, ...
        "TorqueActuationMode","InputTorque", ...
        "MotionActuationMode","ComputedMotion", ...
        "SensePosition","on", ...
        "SenseVelocity","on", ...
        "PositionTargetSpecify","on", ...
        "PositionTargetPriority","High", ...
        "PositionTargetValue",sprintf("rrmInitialQ(%d)",joint), ...
        "PositionTargetValueUnits","rad", ...
        "VelocityTargetSpecify","on", ...
        "VelocityTargetPriority","High", ...
        "VelocityTargetValue",sprintf("rrmInitialDq(%d)",joint), ...
        "VelocityTargetValueUnits","rad/s", ...
        "DampingCoefficient",sprintf("rrmMbDamping(%d)",joint), ...
        "DampingCoefficientUnits","N*m/(rad/s)");
end

add_block("simulink/Signal Routing/Mux",path + "/Position Vector", ...
    "Inputs","2","Position",[880 30 885 95]);
add_block("simulink/Signal Routing/Mux",path + "/Velocity Vector", ...
    "Inputs","2","Position",[880 115 885 180]);
add_block("simulink/Ports & Subsystems/Out1",path + "/q", ...
    "Port","1","Position",[940 55 970 75]);
add_block("simulink/Ports & Subsystems/Out1",path + "/dq", ...
    "Port","2","Position",[940 140 970 160]);
add_block("simulink/Signal Routing/Mux",path + "/End Effector Vector", ...
    "Inputs","3","Position",[880 220 885 310]);
add_block("simulink/Ports & Subsystems/Out1", ...
    path + "/endEffectorPosition", ...
    "Port","3","Position",[940 255 970 275]);

add_block(libraryBlock("sm_lib","World Frame"),path + "/World Frame", ...
    "Position",[20 365 70 415]);
add_block(libraryBlock("sm_lib","Mechanism Configuration"), ...
    path + "/Mechanism Configuration", ...
    "UniformGravity","Constant", ...
    "GravityVector","[0 -rrmGravity 0]", ...
    "GravityVectorUnits","m/s^2", ...
    "Position",[20 445 100 495]);
add_block(libraryBlock("nesl_utility","Solver Configuration"), ...
    path + "/Solver Configuration", ...
    "Position",[20 520 90 570]);

addRigidTransform(path,"Base Transform","[0 0 -0.04]",[125 365 195 415]);
add_block(libraryBlock("sm_lib","Brick Solid"),path + "/Base Solid", ...
    "BrickDimensions","[0.14 0.14 0.08]", ...
    "BrickDimensionsUnits","m", ...
    "BasedOnType","Mass", ...
    "Mass","5", ...
    "MassUnits","kg", ...
    "GraphicDiffuseColor","[0.22 0.24 0.28]", ...
    "Position",[225 365 295 415]);

for joint = 1:2
    y = 365 + (joint-1)*120;
    addRigidTransform(path,"Link "+joint+" Center Transform", ...
        sprintf("[rrmMbLinkLength(%d)/2 0 0]",joint), ...
        [410 y 490 y+45]);
    addRigidTransform(path,"Link "+joint+" Distal Transform", ...
        sprintf("[rrmMbLinkLength(%d) 0 0]",joint), ...
        [410 y+55 490 y+100]);
    solidPath = path + "/Link " + joint + " Solid";
    add_block(libraryBlock("sm_lib","Brick Solid"),solidPath, ...
        "BrickDimensions",sprintf( ...
        "[rrmMbLinkLength(%d) rrmMbWidth rrmMbWidth]",joint), ...
        "BrickDimensionsUnits","m", ...
        "InertiaType","Custom", ...
        "Mass",sprintf("rrmMbLinkMass(%d)",joint), ...
        "MassUnits","kg", ...
        "CenterOfMass","[0 0 0]", ...
        "CenterOfMassUnits","m", ...
        "MomentsOfInertia",sprintf("rrmMbMoments(%d,:)",joint), ...
        "MomentsOfInertiaUnits","kg*m^2", ...
        "ProductsOfInertia","[0 0 0]", ...
        "ProductsOfInertiaUnits","kg*m^2", ...
        "GraphicDiffuseColor",linkColor(joint), ...
        "Position",[545 y 615 y+45]);
end

add_block(libraryBlock("sm_lib","Inertia"),path + "/Payload Inertia", ...
    "InertiaType","PointMass", ...
    "Mass","rrmMbPayload", ...
    "MassUnits","kg", ...
    "GraphicType","Marker", ...
    "MarkerShape","Sphere", ...
    "MarkerSize","0.075", ...
    "GraphicDiffuseColor","[0.82 0.18 0.16]", ...
    "Position",[660 500 735 545]);
sensorPath = path + "/End Effector Sensor";
add_block(libraryBlock("sm_lib","Transform Sensor"),sensorPath, ...
    "MeasurementFrame","World", ...
    "SenseX","on","SenseY","on","SenseZ","on", ...
    "Position",[650 585 730 650]);
coordinateNames = ["X","Y","Z"];
for coordinate = 1:3
    add_block(libraryBlock("nesl_utility","PS-Simulink Converter"), ...
        path + "/End Effector " + coordinateNames(coordinate), ...
        "Unit","m", ...
        "Position",[785 565+coordinate*35 835 590+coordinate*35]);
end
connectPhysicalPlant(path);
end

function connectPhysicalPlant(path)
add_line(path,"tau/1","Torque Split/1");
add_line(path,"Torque Split/1","Torque 1/1");
add_line(path,"Torque Split/2","Torque 2/1");
for joint = 1:2
    add_line(path,"Position "+joint+"/1", ...
        "Position Vector/"+joint);
    add_line(path,"Velocity "+joint+"/1", ...
        "Velocity Vector/"+joint);
    jointPath = path + "/Revolute Joint " + joint;
    connectPorts(path,path+"/Torque "+joint,"RConn",1, ...
        jointPath,"LConn",2);
    connectPorts(path,jointPath,"RConn",2, ...
        path+"/Position "+joint,"LConn",1);
    connectPorts(path,jointPath,"RConn",3, ...
        path+"/Velocity "+joint,"LConn",1);
end
add_line(path,"Position Vector/1","q/1");
add_line(path,"Velocity Vector/1","dq/1");

coordinateNames = ["X","Y","Z"];
for coordinate = 1:3
    connectPorts(path,path+"/End Effector Sensor","RConn",coordinate+1, ...
        path+"/End Effector "+coordinateNames(coordinate),"LConn",1);
    add_line(path,"End Effector "+coordinateNames(coordinate)+"/1", ...
        "End Effector Vector/"+coordinate);
end
add_line(path,"End Effector Vector/1","endEffectorPosition/1");

world = path + "/World Frame";
joint1 = path + "/Revolute Joint 1";
joint2 = path + "/Revolute Joint 2";
connectPorts(path,world,"RConn",1,joint1,"LConn",1);
connectPorts(path,world,"RConn",1, ...
    path+"/Mechanism Configuration","RConn",1);
connectPorts(path,world,"RConn",1, ...
    path+"/Solver Configuration","RConn",1);
connectPorts(path,world,"RConn",1,path+"/Base Transform","LConn",1);
connectPorts(path,path+"/Base Transform","RConn",1, ...
    path+"/Base Solid","RConn",1);

connectPorts(path,joint1,"RConn",1, ...
    path+"/Link 1 Center Transform","LConn",1);
connectPorts(path,path+"/Link 1 Center Transform","RConn",1, ...
    path+"/Link 1 Solid","RConn",1);
connectPorts(path,joint1,"RConn",1, ...
    path+"/Link 1 Distal Transform","LConn",1);
connectPorts(path,path+"/Link 1 Distal Transform","RConn",1, ...
    joint2,"LConn",1);

connectPorts(path,joint2,"RConn",1, ...
    path+"/Link 2 Center Transform","LConn",1);
connectPorts(path,path+"/Link 2 Center Transform","RConn",1, ...
    path+"/Link 2 Solid","RConn",1);
connectPorts(path,joint2,"RConn",1, ...
    path+"/Link 2 Distal Transform","LConn",1);
connectPorts(path,path+"/Link 2 Distal Transform","RConn",1, ...
    path+"/Payload Inertia","RConn",1);
connectPorts(path,world,"RConn",1, ...
    path+"/End Effector Sensor","LConn",1);
connectPorts(path,path+"/Link 2 Distal Transform","RConn",1, ...
    path+"/End Effector Sensor","RConn",1);
end

function connectPorts(system,sourceBlock,sourceSide,sourceIndex, ...
        destinationBlock,destinationSide,destinationIndex)
sourcePorts = get_param(sourceBlock,"PortHandles");
destinationPorts = get_param(destinationBlock,"PortHandles");
add_line(system,sourcePorts.(sourceSide)(sourceIndex), ...
    destinationPorts.(destinationSide)(destinationIndex), ...
    "autorouting","smart");
end

function addRigidTransform(path,name,offset,position)
blockPath = path + "/" + name;
add_block(libraryBlock("sm_lib","Rigid Transform"),blockPath, ...
    "TranslationMethod","Cartesian", ...
    "TranslationCartesianOffset",offset, ...
    "TranslationCartesianOffsetUnits","m", ...
    "Position",position);
end

function color = linkColor(joint)
if joint == 1
    color = "[0.12 0.45 0.78]";
else
    color = "[0.15 0.68 0.42]";
end
end

function source = libraryBlock(library,name)
load_system(library);
matches = find_system(library, ...
    "LookUnderMasks","all", ...
    "FollowLinks","on", ...
    "Name",name);
if numel(matches) ~= 1
    error("rrm:multibody:MissingLibraryBlock", ...
        "Expected exactly one %s block in %s.",name,library);
end
source = string(matches{1});
end

function buildLogging(path)
Simulink.SubSystem.deleteContents(path);
names = ["q","dq","tau","tau_u","endEffectorPosition"];
for index = 1:numel(names)
    y = 30 + (index-1)*50;
    add_block("simulink/Ports & Subsystems/In1", ...
        path + "/" + names(index), ...
        "Port",string(index),"Position",[20 y 50 y+20]);
    add_block("simulink/Sinks/Terminator", ...
        path + "/End " + names(index), ...
        "Position",[130 y 150 y+20]);
    add_line(path,names(index)+"/1","End "+names(index)+"/1");
end
end

function connectTopLevel(modelName)
add_line(modelName,"Reference/1","PID Controller/1");
add_line(modelName,"Reference/2","PID Controller/2");
qLine = add_line(modelName,"Multibody Plant/1", ...
    "PID Controller/3","autorouting","smart");
add_line(modelName,"Multibody Plant/1","Logging/1", ...
    "autorouting","smart");
dqLine = add_line(modelName,"Multibody Plant/2", ...
    "PID Controller/4","autorouting","smart");
add_line(modelName,"Multibody Plant/2","Logging/2", ...
    "autorouting","smart");
tauLine = add_line(modelName,"PID Controller/1", ...
    "Multibody Plant/1","autorouting","smart");
add_line(modelName,"PID Controller/1","Logging/3", ...
    "autorouting","smart");
tauUnsaturatedLine = add_line(modelName,"PID Controller/2", ...
    "Logging/4","autorouting","smart");
endEffectorLine = add_line(modelName,"Multibody Plant/3", ...
    "Logging/5","autorouting","smart");
configureLoggedSignal(qLine,"q");
configureLoggedSignal(dqLine,"dq");
configureLoggedSignal(tauLine,"tau");
configureLoggedSignal(tauUnsaturatedLine,"tauUnsaturated");
configureLoggedSignal(endEffectorLine,"endEffectorPosition");
end

function configureLoggedSignal(lineHandle,name)
displayName = name;
if name == "tauUnsaturated"
    displayName = "tau_u";
elseif name == "endEffectorPosition"
    displayName = "xyz";
end
set_param(lineHandle,"Name",displayName);
sourcePort = get_param(lineHandle,"SrcPortHandle");
set_param(sourcePort, ...
    "DataLogging","on", ...
    "DataLoggingNameMode","Custom", ...
    "DataLoggingName",name);
end

function closeSource(modelName,wasLoaded)
if ~wasLoaded
    closeIfLoaded(modelName);
end
end

function closeIfLoaded(modelName)
if bdIsLoaded(modelName)
    close_system(modelName,0);
end
end
