function comparison = compareRuns(matlabRun,multibodyRun,robot)
%COMPARERUNS Quantify agreement between MATLAB and Multibody executions.
arguments
    matlabRun (1,1) struct
    multibodyRun (1,1) struct
    robot (1,1) struct
end

[matlabTime,matlabData] = validateRun(matlabRun,false);
[multibodyTime,multibodyData] = validateRun(multibodyRun,true);
if ~isequal(size(matlabTime),size(multibodyTime)) || ...
        any(abs(matlabTime-multibodyTime) > ...
        100*eps(max(matlabTime(end),1)))
    error("rrm:multibody:TimeGridMismatch", ...
        "MATLAB and Multibody time grids must match exactly.");
end
sampleTime = matlabTime(2)-matlabTime(1);
if any(abs(diff(matlabTime)-sampleTime) > ...
        100*eps(max(matlabTime(end),1)))
    error("rrm:multibody:TimeGridMismatch", ...
        "Comparison requires a uniform time grid.");
end

matlabEndEffectorPosition = calculateEndEffector(robot,matlabData.q);
qDifference = multibodyData.q-matlabData.q;
dqDifference = multibodyData.dq-matlabData.dq;
tauDifference = multibodyData.tau-matlabData.tau;
endEffectorDifference = ...
    multibodyData.endEffectorPosition-matlabEndEffectorPosition;
qRmsDifference = rmsByChannel(qDifference);
qMaxDifference = max(abs(qDifference),[],2);
dqRmsDifference = rmsByChannel(dqDifference);
dqMaxDifference = max(abs(dqDifference),[],2);
tauRmsDifference = rmsByChannel(tauDifference);
tauMaxDifference = max(abs(tauDifference),[],2);
endEffectorDistance = vecnorm(endEffectorDifference,2,1);
endEffectorRmsDifference = sqrt(mean(endEffectorDistance.^2));
endEffectorMaxDifference = max(endEffectorDistance);
maximumOutOfPlanePosition = ...
    max(abs(multibodyData.endEffectorPosition(3,:)));
matlabSaturationTime = sum(matlabData.saturated,2)*sampleTime;
multibodySaturationTime = sum(multibodyData.saturated,2)*sampleTime;
saturationTimeDifference = abs( ...
    multibodySaturationTime-matlabSaturationTime);

thresholds = struct( ...
    "qRms",1e-3, ...
    "qMax",5e-3, ...
    "dqRms",2e-2, ...
    "tauRms",2e-1, ...
    "endEffectorRms",1e-3, ...
    "endEffectorMax",5e-3, ...
    "planar",1e-9, ...
    "saturationTime",5e-3);
flags = struct( ...
    "qRms",qRmsDifference <= thresholds.qRms, ...
    "qMax",qMaxDifference <= thresholds.qMax, ...
    "dqRms",dqRmsDifference <= thresholds.dqRms, ...
    "tauRms",tauRmsDifference <= thresholds.tauRms, ...
    "endEffectorRms", ...
    endEffectorRmsDifference <= thresholds.endEffectorRms, ...
    "endEffectorMax", ...
    endEffectorMaxDifference <= thresholds.endEffectorMax, ...
    "planar",maximumOutOfPlanePosition <= thresholds.planar, ...
    "saturationTime",saturationTimeDifference <= ...
    thresholds.saturationTime + 10*eps(thresholds.saturationTime), ...
    "completed",matlabRun.status == "completed" && ...
    multibodyRun.status == "completed" && ...
    matlabRun.completedSamples == numel(matlabTime) && ...
    multibodyRun.completedSamples == numel(multibodyTime));

failureSummary = summarizeFailures(flags);
comparison = struct( ...
    "sampleTime",sampleTime, ...
    "thresholds",thresholds, ...
    "qDifference",qDifference, ...
    "dqDifference",dqDifference, ...
    "tauDifference",tauDifference, ...
    "endEffectorDifference",endEffectorDifference, ...
    "matlabEndEffectorPosition",matlabEndEffectorPosition, ...
    "qRmsDifference",qRmsDifference, ...
    "qMaxDifference",qMaxDifference, ...
    "dqRmsDifference",dqRmsDifference, ...
    "dqMaxDifference",dqMaxDifference, ...
    "tauRmsDifference",tauRmsDifference, ...
    "tauMaxDifference",tauMaxDifference, ...
    "endEffectorRmsDifference",endEffectorRmsDifference, ...
    "endEffectorMaxDifference",endEffectorMaxDifference, ...
    "maximumOutOfPlanePosition",maximumOutOfPlanePosition, ...
    "matlabSaturationTime",matlabSaturationTime, ...
    "multibodySaturationTime",multibodySaturationTime, ...
    "saturationTimeDifference",saturationTimeDifference, ...
    "flags",flags, ...
    "pass",strlength(failureSummary) == 0, ...
    "failureSummary",failureSummary);
end

function [time,data] = validateRun(run,requiresEndEffector)
required = ["time","q","dq","tau","saturated","status", ...
    "completedSamples"];
if requiresEndEffector
    required(end+1) = "endEffectorPosition";
end
if ~all(isfield(run,required))
    error("rrm:multibody:InvalidComparisonData", ...
        "Each run must define aligned state, torque, and status fields.");
end
time = run.time;
sampleCount = numel(time);
isValidShape = isequal(size(time),[sampleCount 1]) && sampleCount >= 2 && ...
    isequal(size(run.q),[2 sampleCount]) && ...
    isequal(size(run.dq),[2 sampleCount]) && ...
    isequal(size(run.tau),[2 sampleCount]) && ...
    isequal(size(run.saturated),[2 sampleCount]);
if requiresEndEffector
    isValidShape = isValidShape && ...
        isequal(size(run.endEffectorPosition),[3 sampleCount]);
end
if ~isValidShape || ~isstring(run.status) || ~isscalar(run.status) || ...
        ~isscalar(run.completedSamples) || ~isfinite(run.completedSamples)
    error("rrm:multibody:InvalidComparisonData", ...
        "Run histories and status fields have invalid dimensions or types.");
end
finiteHistory = [time.';run.q;run.dq;run.tau;double(run.saturated)];
if requiresEndEffector
    finiteHistory = [finiteHistory;run.endEffectorPosition];
end
if any(~isfinite(finiteHistory),"all")
    error("rrm:multibody:NonFiniteComparisonData", ...
        "Comparison histories must contain finite data only.");
end
if any(diff(time) <= 0)
    error("rrm:multibody:TimeGridMismatch", ...
        "Comparison time must be strictly increasing.");
end
data = struct( ...
    "q",run.q, ...
    "dq",run.dq, ...
    "tau",run.tau, ...
    "saturated",logical(run.saturated));
if requiresEndEffector
    data.endEffectorPosition = run.endEffectorPosition;
end
end

function position = calculateEndEffector(robot,q)
position = zeros(3,size(q,2));
for sample = 1:size(q,2)
    position(1:2,sample) = rrm.kinematics.forward(robot,q(:,sample));
end
end

function value = rmsByChannel(history)
value = sqrt(mean(history.^2,2));
end

function summary = summarizeFailures(flags)
failures = strings(0,1);
jointLabels = ["q-rms","q-max","dq-rms","tau-rms","saturation"];
jointValues = {flags.qRms,flags.qMax,flags.dqRms, ...
    flags.tauRms,flags.saturationTime};
for metric = 1:numel(jointLabels)
    for joint = 1:2
        if ~jointValues{metric}(joint)
            failures(end+1,1) = ...
                jointLabels(metric) + "-j" + joint; %#ok<AGROW>
        end
    end
end
scalarLabels = ["ee-rms","ee-max","planar","completed"];
scalarValues = [flags.endEffectorRms,flags.endEffectorMax, ...
    flags.planar,flags.completed];
for metric = 1:numel(scalarLabels)
    if ~scalarValues(metric)
        failures(end+1,1) = scalarLabels(metric); %#ok<AGROW>
    end
end
summary = strjoin(failures,", ");
end
