function result = runCrossValidation( ...
        robot, controller, reference, options, modelPath)
%RUNCROSSVALIDATION Run a fixed-gain PID against the Multibody plant.
arguments
    robot (1,1) struct
    controller (1,1) struct
    reference (1,1) struct
    options (1,1) struct
    modelPath (1,1) string
end

validateController(controller);
validateRobot(robot);
sampleTime = validateReference(reference,options);
validateEnvironment(options,reference);
modelPath = resolveModelPath(modelPath);
if ~isfile(modelPath)
    rrm.multibody.buildCrossValidationModel(modelPath);
end
[~,modelName] = fileparts(modelPath);
load_system(modelPath);
cleanup = onCleanup(@() closeIfLoaded(modelName));

simulationInput = Simulink.SimulationInput(modelName);
simulationInput = setModelParameter(simulationInput, ...
    "StopTime",string(reference.time(end)), ...
    "FixedStep",string(sampleTime));
simulationInput = setModelVariable(simulationInput,modelName, ...
    "rrmSampleTime",sampleTime);
simulationInput = setModelVariable(simulationInput,modelName, ...
    "rrmStopTime",reference.time(end));
simulationInput = setModelVariable(simulationInput,modelName, ...
    "rrmQReferenceSignal",timeseries(reference.q.',reference.time));
simulationInput = setModelVariable(simulationInput,modelName, ...
    "rrmDqReferenceSignal",timeseries(reference.dq.',reference.time));
simulationInput = setModelVariable(simulationInput,modelName, ...
    "rrmKp",controller.Kp);
simulationInput = setModelVariable(simulationInput,modelName, ...
    "rrmKi",controller.Ki);
simulationInput = setModelVariable(simulationInput,modelName, ...
    "rrmKd",controller.Kd);
simulationInput = setModelVariable(simulationInput,modelName, ...
    "rrmDerivativeAlpha", ...
    exp(-2*pi*controller.derivativeFilterHz*sampleTime));
simulationInput = setModelVariable(simulationInput,modelName, ...
    "rrmAntiWindupGain",controller.antiWindupGain);
torqueLimits = min(controller.torqueLimits,robot.torqueLimits);
simulationInput = setModelVariable(simulationInput,modelName, ...
    "rrmTorqueLimits",torqueLimits);
simulationInput = setModelVariable(simulationInput,modelName, ...
    "rrmInitialQ",reference.q(:,1));
simulationInput = setModelVariable(simulationInput,modelName, ...
    "rrmInitialDq",options.initialVelocity);
simulationInput = setPhysicalVariables( ...
    simulationInput,modelName,robot);

toolchainWarning = "coder_compile:toolchain:DefaultToolchainNotInRegistry";
warningState = warning("query",toolchainWarning);
warning("off",toolchainWarning);
warningCleanup = onCleanup(@() warning(warningState));
simulationOutput = sim(simulationInput);
clear warningCleanup

logs = simulationOutput.logsout;
[time,q] = readLoggedSignal(logs,"q",2);
[dqTime,dq] = readLoggedSignal(logs,"dq",2);
[tauTime,tau] = readLoggedSignal(logs,"tau",2);
[unsaturatedTime,tauUnsaturated] = readLoggedSignal( ...
    logs,"tauUnsaturated",2);
[positionTime,endEffectorPosition] = readLoggedSignal( ...
    logs,"endEffectorPosition",3);
validateOutputGrids(reference.time,time,dqTime,tauTime, ...
    unsaturatedTime,positionTime);
if any(~isfinite([q;dq;tau;tauUnsaturated;endEffectorPosition]),"all")
    error("rrm:multibody:NonFiniteOutput", ...
        "Multibody simulation returned one or more non-finite samples.");
end
saturated = abs(tauUnsaturated-tau) > ...
    100*eps(max(abs(tau),1));

result = struct( ...
    "time",time, ...
    "q",q, ...
    "dq",dq, ...
    "qReference",reference.q, ...
    "dqReference",reference.dq, ...
    "tau",tau, ...
    "tauUnsaturated",tauUnsaturated, ...
    "saturated",saturated, ...
    "endEffectorPosition",endEffectorPosition, ...
    "status","completed", ...
    "completedSamples",numel(time), ...
    "modelName",string(modelName));
clear cleanup
end

function simulationInput = setPhysicalVariables( ...
        simulationInput,modelName,robot)
width = 0.06;
transverse = max(1e-6,0.01*robot.inertia);
moments = [transverse robot.inertia robot.inertia];
names = ["rrmGravity","rrmMbLinkLength","rrmMbLinkMass", ...
    "rrmMbCenterOfMass","rrmMbLinkInertia","rrmMbPayload", ...
    "rrmMbDamping","rrmMbWidth","rrmMbMoments"];
values = {robot.gravity,[robot.L1;robot.L2],[robot.m1;robot.m2], ...
    robot.com,robot.inertia,robot.payload,robot.viscousFriction, ...
    width,moments};
for index = 1:numel(names)
    simulationInput = setModelVariable(simulationInput,modelName, ...
        names(index),values{index});
end
end

function simulationInput = setModelVariable( ...
        simulationInput,modelName,name,value)
simulationInput = setVariable(simulationInput,name,value, ...
    Workspace=modelName);
end

function validateRobot(robot)
required = ["L1","L2","m1","m2","payload","com","inertia", ...
    "gravity","viscousFriction","torqueLimits"];
if ~all(isfield(robot,required))
    error("rrm:multibody:InvalidRobot", ...
        "Robot is missing required physical parameters.");
end
vectors = {[robot.L1;robot.L2],[robot.m1;robot.m2],robot.com, ...
    robot.inertia,robot.viscousFriction,robot.torqueLimits};
if any(cellfun(@(value) ~isequal(size(value),[2 1]) || ...
        ~isreal(value) || any(~isfinite(value)),vectors)) || ...
        any(vectors{1} <= 0) || any(vectors{2} <= 0) || ...
        any(vectors{3} < 0) || any(vectors{3} > vectors{1}) || ...
        any(vectors{4} <= 0) || any(vectors{5} < 0) || ...
        any(vectors{6} <= 0) || ...
        ~isscalar(robot.payload) || ~isfinite(robot.payload) || ...
        robot.payload < 0 || ~isscalar(robot.gravity) || ...
        ~isfinite(robot.gravity) || robot.gravity <= 0
    error("rrm:multibody:InvalidRobot", ...
        "Robot physical parameters are invalid.");
end
end

function validateController(controller)
required = ["type","Kp","Ki","Kd","derivativeFilterHz", ...
    "antiWindupGain","torqueLimits"];
if ~all(isfield(controller,required)) || controller.type ~= "pid"
    error("rrm:multibody:UnsupportedController", ...
        "Phase 6B supports fixed-gain PID controllers only.");
end
vectors = {controller.Kp,controller.Ki,controller.Kd, ...
    controller.antiWindupGain,controller.torqueLimits};
if any(cellfun(@(value) ~isequal(size(value),[2 1]) || ...
        ~isreal(value) || any(~isfinite(value)) || any(value < 0),vectors)) || ...
        ~isscalar(controller.derivativeFilterHz) || ...
        ~isfinite(controller.derivativeFilterHz) || ...
        controller.derivativeFilterHz <= 0
    error("rrm:multibody:UnsupportedController", ...
        "Fixed-gain PID parameters must be finite and nonnegative.");
end
end

function sampleTime = validateReference(reference,options)
requiredReference = ["time","q","dq","ddq"];
if ~all(isfield(reference,requiredReference)) || ...
        ~isfield(options,"sampleTime") || ...
        ~isfield(options,"initialVelocity")
    error("rrm:multibody:InvalidReference", ...
        "Reference or simulation options are incomplete.");
end
sampleTime = options.sampleTime;
sampleCount = numel(reference.time);
isValidArrays = isequal(size(reference.time),[sampleCount 1]) && ...
    isequal(size(reference.q),[2 sampleCount]) && ...
    isequal(size(reference.dq),[2 sampleCount]) && ...
    isequal(size(reference.ddq),[2 sampleCount]) && ...
    all(isfinite([reference.time.';reference.q;reference.dq;reference.ddq]),"all");
isValidStep = isscalar(sampleTime) && isfinite(sampleTime) && ...
    sampleTime > 0 && sampleTime == 0.001 && ...
    all(abs(diff(reference.time)-sampleTime) <= ...
    100*eps(max(reference.time(end),1)));
if ~isValidArrays || sampleCount < 2 || ~isValidStep || ...
        ~isequal(size(options.initialVelocity),[2 1]) || ...
        any(~isfinite(options.initialVelocity))
    error("rrm:multibody:InvalidReference", ...
        "Reference must use finite aligned arrays on the 1 ms grid.");
end
end

function validateEnvironment(options,reference)
sampleCount = numel(reference.time);
if ~isfield(options,"disturbanceTorque") || ...
        ~isZeroHistory(options.disturbanceTorque,sampleCount)
    error("rrm:multibody:UnsupportedEnvironment", ...
        "Phase 6B requires zero disturbance torque.");
end
if isfield(options,"measurementNoise")
    noise = options.measurementNoise;
    if ~isstruct(noise) || ~all(isfield(noise,["position","velocity"])) || ...
            ~isZeroHistory(noise.position,sampleCount) || ...
            ~isZeroHistory(noise.velocity,sampleCount)
        error("rrm:multibody:UnsupportedEnvironment", ...
            "Phase 6B requires zero measurement noise.");
    end
end
end

function valid = isZeroHistory(value,sampleCount)
valid = isnumeric(value) && isreal(value) && ...
    (isequal(size(value),[2 1]) || isequal(size(value),[2 sampleCount])) && ...
    all(isfinite(value),"all") && all(value == 0,"all");
end

function modelPath = resolveModelPath(modelPath)
if ~java.io.File(char(modelPath)).isAbsolute()
    functionPath = mfilename("fullpath");
    projectRoot = fileparts(fileparts(fileparts(functionPath)));
    modelPath = fullfile(projectRoot,modelPath);
end
[~,name,extension] = fileparts(modelPath);
if ~strcmpi(extension,".slx") || strlength(name) == 0 || ~isvarname(name)
    error("rrm:multibody:InvalidModelPath", ...
        "Model path must name a valid .slx file.");
end
modelPath = string(java.io.File(char(modelPath)).getCanonicalPath());
end

function [time,data] = readLoggedSignal(logs,name,channelCount)
element = logs.get(name);
if isempty(element)
    error("rrm:multibody:MissingLoggedSignal", ...
        "Logged signal '%s' is missing.",name);
end
values = element.Values;
time = values.Time;
data = squeeze(values.Data);
if size(data,1) == numel(time)
    data = data.';
end
if ~isequal(size(data),[channelCount numel(time)])
    error("rrm:multibody:MissingLoggedSignal", ...
        "Logged signal '%s' must have %d channels.",name,channelCount);
end
end

function validateOutputGrids(referenceTime,varargin)
for grid = varargin
    time = grid{1};
    if ~isequal(size(time),size(referenceTime)) || ...
            any(abs(time-referenceTime) > ...
            100*eps(max(referenceTime(end),1)))
        error("rrm:multibody:TimeGridMismatch", ...
            "Multibody output time grid does not match the reference.");
    end
end
end

function closeIfLoaded(modelName)
if bdIsLoaded(modelName)
    close_system(modelName,0);
end
end
