function scenarios = makeStochasticScenarios(reference, baseOptions, mode)
%MAKESTOCHASTICSCENARIOS Define prescribed Phase 4B noise scenarios.
arguments
    reference (1,1) struct
    baseOptions (1,1) struct
    mode (1,1) string {mustBeMember(mode,["full","smoke"])} = "full"
end

validateInputs(reference, baseOptions);
sampleCount = numel(reference.time);
options = baseOptions;
if isfield(options, "measurementNoise")
    options = rmfield(options, "measurementNoise");
end
options.disturbanceTorque = zeros(2,sampleCount);
baseline = rrm.config.makeRobot("baseline");
seeds = 42001:42030;

lowNoise = noiseSpec(0.05,0.5);
mediumNoise = noiseSpec(0.20,2.0);
highNoise = noiseSpec(0.50,5.0);
scenarios = [ ...
    makeScenario("noise-low","noise",baseline,options,lowNoise,seeds, ...
        [NaN;NaN],1,1,1), ...
    makeScenario("noise-medium","noise",baseline,options, ...
        mediumNoise,seeds,[NaN;NaN],1,1,1), ...
    makeScenario("noise-high","noise",baseline,options,highNoise,seeds, ...
        [NaN;NaN],1,1,1), ...
    makeCombined(reference,options,mediumNoise,seeds)];

validateScenarios(scenarios, sampleCount);
if mode == "smoke"
    scenarios = scenarios([2 4]);
    for index = 1:numel(scenarios)
        scenarios(index).seeds = 42001:42002;
    end
end
end

function spec = noiseSpec(positionDegrees, velocityDegrees)
spec = struct( ...
    "positionStd", deg2rad(positionDegrees)*ones(2,1), ...
    "velocityStd", deg2rad(velocityDegrees)*ones(2,1));
end

function scenario = makeCombined(reference, options, noise, seeds)
robot = rrm.config.makeRobot("extended");
robot.payload = 1.0;
robot.m1 = 1.2*robot.m1;
robot.m2 = 1.2*robot.m2;
robot.inertia = 1.2*robot.inertia;
baseline = rrm.config.makeRobot("baseline");
baseTorque = baseline.torqueLimits;
robot.torqueLimits = [18;10];
active = reference.time >= 2.00 & reference.time <= 2.10;
options.disturbanceTorque(:,active) = repmat([4;-3],1,nnz(active));
lengthScale = (robot.L1+robot.L2)/(baseline.L1+baseline.L2);
torqueScale = mean(robot.torqueLimits./baseTorque);
scenario = makeScenario("combined-stochastic","combined", ...
    robot,options,noise,seeds,[2;2.1],lengthScale,1.2,torqueScale);
end

function scenario = makeScenario(name, category, robot, options, noise, ...
        seeds, disturbanceWindow, lengthScale, uncertaintyScale, torqueScale)
scenario = struct( ...
    "name", name, ...
    "category", category, ...
    "robot", robot, ...
    "options", options, ...
    "noise", noise, ...
    "seeds", seeds, ...
    "disturbanceWindow", disturbanceWindow, ...
    "recoveryBand", deg2rad(2), ...
    "recoveryDwell", 0.10, ...
    "payload", robot.payload, ...
    "lengthScale", lengthScale, ...
    "uncertaintyScale", uncertaintyScale, ...
    "torqueScale", torqueScale);
end

function validateInputs(reference, options)
if ~isfield(reference,"time") || ~iscolumn(reference.time) || ...
        isempty(reference.time) || any(~isfinite(reference.time))
    error("rrm:robustness:InvalidReference", ...
        "Reference must contain a finite nonempty time column.");
end
required = ["sampleTime","initialVelocity","disturbanceTorque", ...
    "successCriteria"];
if ~all(isfield(options,required))
    error("rrm:robustness:InvalidOptions", ...
        "Base options are missing required fields.");
end
end

function validateScenarios(scenarios, sampleCount)
if numel(unique([scenarios.name])) ~= numel(scenarios)
    error("rrm:robustness:InvalidStochasticScenario", ...
        "Stochastic scenario names must be unique.");
end
for index = 1:numel(scenarios)
    scenario = scenarios(index);
    physical = [scenario.robot.L1;scenario.robot.L2; ...
        scenario.robot.m1;scenario.robot.m2;scenario.robot.payload; ...
        scenario.robot.inertia;scenario.robot.torqueLimits];
    noiseValues = [scenario.noise.positionStd; ...
        scenario.noise.velocityStd];
    if any(~isfinite(physical)) || any(physical < 0) || ...
            any(~isfinite(noiseValues)) || any(noiseValues < 0) || ...
            ~isequal(size(scenario.options.disturbanceTorque), ...
            [2 sampleCount]) || numel(unique(scenario.seeds)) ~= ...
            numel(scenario.seeds)
        error("rrm:robustness:InvalidStochasticScenario", ...
            "Scenario %s contains invalid data.",scenario.name);
    end
end
end
