function configuration = makePidOptimization(baseController)
%MAKEPIDOPTIMIZATION Create reproducible bounded PID tuning settings.
arguments
    baseController (1,1) struct
end

requiredGains = ["Kp", "Ki", "Kd"];
if ~all(isfield(baseController, requiredGains))
    error("rrm:optimization:InvalidConfiguration", ...
        "The base controller must define Kp, Ki, and Kd.");
end

configuration = struct( ...
    "variableOrder", ["Kp1";"Kp2";"Ki1";"Ki2";"Kd1";"Kd2"], ...
    "initialMultipliers", ones(6,1), ...
    "lowerBounds", [0.5;0.5;0.25;0.25;0.5;0.5], ...
    "upperBounds", 2*ones(6,1), ...
    "objectiveWeights", struct( ...
        "trackingRms", 0.50, ...
        "overshoot", 0.10, ...
        "torqueRms", 0.15, ...
        "settlingTime", 0.25), ...
    "saturationPenalty", 100, ...
    "failurePenalty", 100, ...
    "settlingBand", deg2rad(2), ...
    "solver", struct( ...
        "algorithm", "sqp", ...
        "maxIterations", 20, ...
        "maxFunctionEvaluations", 150, ...
        "stepTolerance", 1e-4, ...
        "optimalityTolerance", 1e-3, ...
        "finiteDifferenceType", "forward", ...
        "useParallel", false, ...
        "display", "iter"));
end
