function controller = makePidController(robot)
%MAKEPIDCONTROLLER Create the nominal independent-joint PID controller.
arguments
    robot (1,1) struct
end

controller = struct( ...
    "name", "manual-pid", ...
    "Kp", [120; 100], ...
    "Ki", [40; 30], ...
    "Kd", [25; 18], ...
    "derivativeFilterHz", 50, ...
    "antiWindupGain", [0.002; 0.002], ...
    "torqueLimits", robot.torqueLimits);
end
