function options = makeSimulationOptions()
%MAKESIMULATIONOPTIONS Create deterministic nominal simulation settings.
options = struct( ...
    "sampleTime", 0.001, ...
    "initialVelocity", [0; 0], ...
    "disturbanceTorque", [0; 0], ...
    "successCriteria", struct( ...
        "steadyStateWindow", 0.5, ...
        "steadyStateRmsError", [0.02; 0.02], ...
        "steadyStateMaxAbsError", [0.05; 0.05]));
end
