function [objective, components] = scorePidResult( ...
        result, robot, reference, configuration)
%SCOREPIDRESULT Calculate the dimensionless PID tuning objective.
arguments
    result (1,1) struct
    robot (1,1) struct
    reference (1,1) struct
    configuration (1,1) struct
end

validateInputs(result, robot, reference, configuration);
travel = abs(reference.q(:,end)-reference.q(:,1));
if any(travel <= 100*eps(max(travel,1)))
    error("rrm:optimization:ZeroTravel", ...
        "Every optimized joint must have nonzero commanded travel.");
end

sampleCount = numel(reference.time);
validSamples = isfinite(result.time(:).') & ...
    all(isfinite(result.q),1) & ...
    all(isfinite(result.qReference),1) & ...
    all(isfinite(result.tau),1);
validFraction = nnz(validSamples)/sampleCount;

if any(validSamples)
    q = result.q(:,validSamples);
    qReference = result.qReference(:,validSamples);
    tau = result.tau(:,validSamples);
    normalizedError = (qReference-q)./travel;
    trackingRms = mean(sqrt(mean(normalizedError.^2,2)));

    direction = sign(reference.q(:,end)-reference.q(:,1));
    projectedOvershoot = (q-reference.q(:,end)).*direction;
    overshoot = mean(max(max(projectedOvershoot,[],2),0)./travel);

    normalizedTorque = tau./robot.torqueLimits;
    torqueRms = mean(sqrt(mean(normalizedTorque.^2,2)));
    settlingTime = calculateSettlingTime( ...
        result, reference, validSamples, configuration.settlingBand);
else
    trackingRms = 1;
    overshoot = 1;
    torqueRms = 1;
    settlingTime = 1;
end

saturationFraction = mean(double(result.saturated), "all");
failurePenalty = configuration.failurePenalty * ...
    (double(result.status ~= "completed") + (1-validFraction));
weights = configuration.objectiveWeights;
weighted = [ ...
    weights.trackingRms*trackingRms; ...
    weights.overshoot*overshoot; ...
    weights.torqueRms*torqueRms; ...
    weights.settlingTime*settlingTime];
objective = sum(weighted) + ...
    configuration.saturationPenalty*saturationFraction + failurePenalty;

components = struct( ...
    "trackingRms", trackingRms, ...
    "overshoot", overshoot, ...
    "torqueRms", torqueRms, ...
    "settlingTime", settlingTime, ...
    "saturationFraction", saturationFraction, ...
    "failurePenalty", failurePenalty, ...
    "weighted", weighted, ...
    "total", objective);
end

function normalizedTime = calculateSettlingTime( ...
        result, reference, validSamples, settlingBand)
duration = reference.time(end)-reference.time(1);
q = result.q(:,validSamples);
time = result.time(validSamples);
target = reference.q(:,end);
jointSettlingTime = zeros(2,1);
for joint = 1:2
    outside = find(abs(q(joint,:)-target(joint)) > settlingBand, 1, "last");
    if isempty(outside)
        jointSettlingTime(joint) = 0;
    elseif outside < numel(time)
        jointSettlingTime(joint) = time(outside+1)-reference.time(1);
    else
        jointSettlingTime(joint) = duration;
    end
end
normalizedTime = mean(jointSettlingTime)/duration;
end

function validateInputs(result, robot, reference, configuration)
requiredResult = ["time","q","qReference","tau","saturated","status"];
requiredReference = ["time","q"];
requiredConfiguration = ["objectiveWeights","saturationPenalty", ...
    "failurePenalty","settlingBand"];
sampleCount = numel(reference.time);
validShape = all(isfield(result,requiredResult)) && ...
    all(isfield(reference,requiredReference)) && ...
    isequal(size(result.q),[2 sampleCount]) && ...
    isequal(size(result.qReference),[2 sampleCount]) && ...
    isequal(size(result.tau),[2 sampleCount]) && ...
    isequal(size(result.saturated),[2 sampleCount]) && ...
    isequal(size(reference.q),[2 sampleCount]);
if ~validShape || ~isfield(robot,"torqueLimits") || ...
        ~all(isfield(configuration,requiredConfiguration))
    error("rrm:optimization:InvalidScoringInput", ...
        "Result, robot, reference, or objective configuration is invalid.");
end
weights = configuration.objectiveWeights;
weightNames = ["trackingRms","overshoot","torqueRms","settlingTime"];
weightValues = zeros(4,1);
if ~isstruct(weights) || ~all(isfield(weights,weightNames))
    error("rrm:optimization:InvalidConfiguration", ...
        "All objective weights must be defined.");
end
for index = 1:4
    weightValues(index) = weights.(weightNames(index));
end
if any(~isfinite(weightValues)) || any(weightValues < 0) || ...
        abs(sum(weightValues)-1) > 1e-12 || ...
        ~isscalar(configuration.saturationPenalty) || ...
        configuration.saturationPenalty < 0 || ...
        ~isscalar(configuration.failurePenalty) || ...
        configuration.failurePenalty < 0 || ...
        ~isscalar(configuration.settlingBand) || ...
        ~isfinite(configuration.settlingBand) || configuration.settlingBand <= 0 || ...
        any(~isfinite(robot.torqueLimits)) || any(robot.torqueLimits <= 0)
    error("rrm:optimization:InvalidConfiguration", ...
        "Objective weights, penalties, band, and torque limits must be valid.");
end
duration = reference.time(end)-reference.time(1);
if ~isfinite(duration) || duration <= 0
    error("rrm:optimization:InvalidScoringInput", ...
        "Reference duration must be finite and positive.");
end
end
