function report = tunePid( ...
        robot, baseController, reference, simulationOptions, configuration)
%TUNEPID Tune six PID gain multipliers with bounded deterministic fmincon.
arguments
    robot (1,1) struct
    baseController (1,1) struct
    reference (1,1) struct
    simulationOptions (1,1) struct
    configuration (1,1) struct
end

if isempty(which("fmincon"))
    error("rrm:optimization:MissingFmincon", ...
        "Optimization Toolbox fmincon is required for PID tuning.");
end
validateConfiguration(configuration);

history = struct( ...
    "multipliers", {}, ...
    "objective", {}, ...
    "status", {}, ...
    "components", {});
initialController = rrm.optimization.applyPidMultipliers( ...
    baseController, configuration.initialMultipliers, configuration);
initialResult = rrm.simulation.runPid( ...
    robot, initialController, reference, simulationOptions);
[initialObjective, initialComponents] = ...
    rrm.optimization.scorePidResult( ...
        initialResult, robot, reference, configuration);

solver = configuration.solver;
solverOptions = optimoptions("fmincon", ...
    "Algorithm", solver.algorithm, ...
    "Display", solver.display, ...
    "MaxIterations", solver.maxIterations, ...
    "MaxFunctionEvaluations", solver.maxFunctionEvaluations, ...
    "StepTolerance", solver.stepTolerance, ...
    "OptimalityTolerance", solver.optimalityTolerance, ...
    "FiniteDifferenceType", solver.finiteDifferenceType, ...
    "UseParallel", solver.useParallel);

[finalMultipliers, solverObjective, exitFlag, solverOutput] = fmincon( ...
    @evaluateCandidate, configuration.initialMultipliers, ...
    [], [], [], [], configuration.lowerBounds, ...
    configuration.upperBounds, [], solverOptions);

finalController = rrm.optimization.applyPidMultipliers( ...
    baseController, finalMultipliers, configuration);
finalResult = rrm.simulation.runPid( ...
    robot, finalController, reference, simulationOptions);
[finalObjective, finalComponents] = ...
    rrm.optimization.scorePidResult( ...
        finalResult, robot, reference, configuration);

report = struct( ...
    "initialMultipliers", configuration.initialMultipliers, ...
    "finalMultipliers", finalMultipliers, ...
    "initialObjective", initialObjective, ...
    "finalObjective", finalObjective, ...
    "solverObjective", solverObjective, ...
    "initialComponents", initialComponents, ...
    "finalComponents", finalComponents, ...
    "controller", finalController, ...
    "exitFlag", exitFlag, ...
    "solverOutput", solverOutput, ...
    "history", history, ...
    "finalResult", finalResult);

    function objective = evaluateCandidate(multipliers)
        candidate = rrm.optimization.applyPidMultipliers( ...
            baseController, multipliers, configuration);
        candidateResult = rrm.simulation.runPid( ...
            robot, candidate, reference, simulationOptions);
        [objective, components] = rrm.optimization.scorePidResult( ...
            candidateResult, robot, reference, configuration);
        history(end+1) = struct( ...
            "multipliers", multipliers, ...
            "objective", objective, ...
            "status", candidateResult.status, ...
            "components", components);
    end
end

function validateConfiguration(configuration)
requiredFields = ["initialMultipliers","lowerBounds", ...
    "upperBounds","solver"];
solverFields = ["algorithm","display","maxIterations", ...
    "maxFunctionEvaluations","stepTolerance","optimalityTolerance", ...
    "finiteDifferenceType","useParallel"];
if ~all(isfield(configuration,requiredFields)) || ...
        ~isstruct(configuration.solver) || ...
        ~all(isfield(configuration.solver,solverFields)) || ...
        ~isequal(size(configuration.initialMultipliers),[6 1]) || ...
        ~isequal(size(configuration.lowerBounds),[6 1]) || ...
        ~isequal(size(configuration.upperBounds),[6 1]) || ...
        any(~isfinite(configuration.initialMultipliers)) || ...
        any(configuration.initialMultipliers < configuration.lowerBounds) || ...
        any(configuration.initialMultipliers > configuration.upperBounds)
    error("rrm:optimization:InvalidConfiguration", ...
        "PID optimization decision and solver settings are invalid.");
end
solver = configuration.solver;
if solver.maxIterations < 1 || solver.maxIterations ~= fix(solver.maxIterations) || ...
        solver.maxFunctionEvaluations < 1 || ...
        solver.maxFunctionEvaluations ~= fix(solver.maxFunctionEvaluations) || ...
        solver.stepTolerance <= 0 || ~isfinite(solver.stepTolerance) || ...
        solver.optimalityTolerance <= 0 || ...
        ~isfinite(solver.optimalityTolerance) || ~isscalar(solver.useParallel)
    error("rrm:optimization:InvalidConfiguration", ...
        "PID optimization decision and solver settings are invalid.");
end
end
