function modelName = buildPidCrossValidationModel(modelPath)
%BUILDPIDCROSSVALIDATIONMODEL Build the native PID validation model.
arguments
    modelPath (1,1) string
end

if isempty(which("new_system"))
    error("rrm:simulink:MissingSimulink", ...
        "Simulink is required to build the cross-validation model.");
end
if ~java.io.File(char(modelPath)).isAbsolute()
    functionPath = mfilename("fullpath");
    projectRoot = fileparts(fileparts(fileparts(functionPath)));
    modelPath = fullfile(projectRoot,modelPath);
end
[parent,name,extension] = fileparts(modelPath);
if ~strcmpi(extension,".slx") || strlength(name) == 0 || ...
        ~isvarname(name)
    error("rrm:simulink:InvalidModelPath", ...
        "Model path must name a valid .slx file.");
end
if strlength(parent) == 0
    parent = ".";
end
if ~isfolder(parent)
    [created,message] = mkdir(parent);
    if ~created
        error("rrm:simulink:InvalidModelPath", ...
            "Unable to create model directory: %s", message);
    end
end
parent = string(java.io.File(char(parent)).getCanonicalPath());
modelPath = fullfile(parent,name + extension);
modelName = string(name);

if bdIsLoaded(modelName)
    close_system(modelName,0);
end
if isfile(modelPath)
    delete(modelPath);
end

new_system(modelName);
cleanup = onCleanup(@() closeIfLoaded(modelName));
set_param(modelName, ...
    "SolverType","Fixed-step", ...
    "Solver","ode4", ...
    "FixedStep","0.001", ...
    "StopTime","rrmStopTime", ...
    "SignalLogging","on", ...
    "ReturnWorkspaceOutputs","on");

addTopLevelSubsystem(modelName,"Reference",[40 100 210 250]);
addTopLevelSubsystem(modelName,"PID Controller",[280 80 470 270]);
addTopLevelSubsystem(modelName,"Two-Link Plant",[560 80 750 270]);
addTopLevelSubsystem(modelName,"Logging",[830 100 980 250]);
buildReference(modelName + "/Reference");
buildController(modelName + "/PID Controller");
buildPlant(modelName + "/Two-Link Plant");
buildLogging(modelName + "/Logging");
connectTopLevel(modelName);
assignDefaultParameters(modelName);
addModelAnnotation(modelName);
save_system(modelName,modelPath);
end

function addTopLevelSubsystem(modelName, blockName, position)
add_block("simulink/Ports & Subsystems/Subsystem", ...
    modelName + "/" + blockName, ...
    "Position",position);
end

function buildReference(path)
Simulink.SubSystem.deleteContents(path);
add_block("simulink/Sources/From Workspace",path + "/q Reference", ...
    "VariableName","rrmQReferenceSignal", ...
    "Interpolate","off", ...
    "OutputAfterFinalValue","Holding final value", ...
    "Position",[35 45 165 75]);
add_block("simulink/Sources/From Workspace",path + "/dq Reference", ...
    "VariableName","rrmDqReferenceSignal", ...
    "Interpolate","off", ...
    "OutputAfterFinalValue","Holding final value", ...
    "Position",[35 115 165 145]);
add_block("simulink/Ports & Subsystems/Out1",path + "/qRef", ...
    "Port","1","Position",[240 50 270 70]);
add_block("simulink/Ports & Subsystems/Out1",path + "/dqRef", ...
    "Port","2","Position",[240 120 270 140]);
add_line(path,"q Reference/1","qRef/1");
add_line(path,"dq Reference/1","dqRef/1");
end

function buildController(path)
Simulink.SubSystem.deleteContents(path);
inputNames = ["qRef","dqRef","q","dq"];
for index = 1:numel(inputNames)
    y = 35 + (index-1)*55;
    add_block("simulink/Ports & Subsystems/In1", ...
        path + "/" + inputNames(index), ...
        "Port",string(index),"Position",[20 y 50 y+20]);
    add_block("simulink/Discrete/Zero-Order Hold", ...
        path + "/Hold " + inputNames(index), ...
        "SampleTime","rrmSampleTime", ...
        "Position",[75 y-5 120 y+25]);
    add_line(path,inputNames(index) + "/1", ...
        "Hold " + inputNames(index) + "/1");
end
add_block("simulink/Math Operations/Sum",path + "/Error", ...
    "Inputs","+-","Position",[155 40 180 65]);
add_block("simulink/Math Operations/Sum",path + "/Rate Error", ...
    "Inputs","+-","Position",[155 95 180 120]);
add_line(path,"Hold qRef/1","Error/1");
add_line(path,"Hold q/1","Error/2");
add_line(path,"Hold dqRef/1","Rate Error/1");
add_line(path,"Hold dq/1","Rate Error/2");

add_block("simulink/Discrete/Discrete Transfer Fcn", ...
    path + "/Derivative Filter", ...
    "Numerator","1-rrmDerivativeAlpha", ...
    "Denominator","[1 -rrmDerivativeAlpha]", ...
    "SampleTime","rrmSampleTime", ...
    "Position",[220 90 330 125]);
add_line(path,"Rate Error/1","Derivative Filter/1");

add_block("simulink/Math Operations/Gain",path + "/Kp", ...
    "Gain","rrmKp","Multiplication","Element-wise(K.*u)", ...
    "Position",[235 25 305 60]);
add_block("simulink/Math Operations/Gain",path + "/Ki", ...
    "Gain","rrmKi","Multiplication","Element-wise(K.*u)", ...
    "Position",[365 150 435 185]);
add_block("simulink/Math Operations/Gain",path + "/Kd", ...
    "Gain","rrmKd","Multiplication","Element-wise(K.*u)", ...
    "Position",[365 90 435 125]);
add_line(path,"Error/1","Kp/1");
add_line(path,"Derivative Filter/1","Kd/1");

add_block("simulink/Discrete/Discrete-Time Integrator", ...
    path + "/Integral State", ...
    "IntegratorMethod","Integration: Forward Euler", ...
    "gainval","1", ...
    "InitialCondition","zeros(2,1)", ...
    "SampleTime","rrmSampleTime", ...
    "Position",[235 150 315 185]);
add_line(path,"Integral State/1","Ki/1");

add_block("simulink/Math Operations/Sum", ...
    path + "/Unsaturated Torque", ...
    "Inputs","+++","Position",[480 65 505 140]);
add_line(path,"Kp/1","Unsaturated Torque/1");
add_line(path,"Kd/1","Unsaturated Torque/2");
add_line(path,"Ki/1","Unsaturated Torque/3");
add_block("simulink/Discontinuities/Saturation",path + "/Torque Limit", ...
    "UpperLimit","rrmTorqueLimits", ...
    "LowerLimit","-rrmTorqueLimits", ...
    "Position",[545 85 615 120]);
add_line(path,"Unsaturated Torque/1","Torque Limit/1");

add_block("simulink/Math Operations/Sum", ...
    path + "/Saturation Residual", ...
    "Inputs","+-","Position",[545 170 570 205]);
add_block("simulink/Math Operations/Gain",path + "/Anti Windup", ...
    "Gain","rrmAntiWindupGain", ...
    "Multiplication","Element-wise(K.*u)", ...
    "Position",[455 175 515 205]);
add_block("simulink/Math Operations/Sum", ...
    path + "/Integral Derivative", ...
    "Inputs","++","Position",[365 200 390 235]);
add_line(path,"Torque Limit/1","Saturation Residual/1", ...
    "autorouting","on");
add_line(path,"Unsaturated Torque/1","Saturation Residual/2", ...
    "autorouting","on");
add_line(path,"Saturation Residual/1","Anti Windup/1");
add_line(path,"Anti Windup/1","Integral Derivative/2", ...
    "autorouting","on");
add_line(path,"Error/1","Integral Derivative/1", ...
    "autorouting","on");
add_line(path,"Integral Derivative/1","Integral State/1", ...
    "autorouting","on");

add_block("simulink/Ports & Subsystems/Out1",path + "/tau", ...
    "Port","1","Position",[665 90 695 110]);
add_line(path,"Torque Limit/1","tau/1");
add_block("simulink/Ports & Subsystems/Out1",path + "/tauUnsaturated", ...
    "Port","2","Position",[665 135 695 155]);
add_line(path,"Unsaturated Torque/1","tauUnsaturated/1", ...
    "autorouting","on");
end

function buildPlant(path)
Simulink.SubSystem.deleteContents(path);
add_block("simulink/Ports & Subsystems/In1",path + "/tau", ...
    "Port","1","Position",[20 105 50 125]);
add_block("simulink/Sources/Constant",path + "/Physical Parameters", ...
    "Value","rrmPlantParameters", ...
    "Position",[20 180 115 215]);
add_block("simulink/User-Defined Functions/MATLAB Function", ...
    path + "/Dynamics","Position",[165 75 300 185]);
chart = find(sfroot,"-isa","Stateflow.EMChart", ...
    "Path",path + "/Dynamics");
chart.Script = plantScript();
add_block("simulink/Continuous/Integrator",path + "/Joint Velocity", ...
    "InitialCondition","rrmInitialDq", ...
    "Position",[350 115 395 155]);
add_block("simulink/Continuous/Integrator",path + "/Joint Position", ...
    "InitialCondition","rrmInitialQ", ...
    "Position",[455 115 500 155]);
add_block("simulink/Ports & Subsystems/Out1",path + "/q", ...
    "Port","1","Position",[565 100 595 120]);
add_block("simulink/Ports & Subsystems/Out1",path + "/dq", ...
    "Port","2","Position",[565 155 595 175]);
add_line(path,"tau/1","Dynamics/3","autorouting","on");
add_line(path,"Physical Parameters/1","Dynamics/4");
add_line(path,"Dynamics/1","Joint Velocity/1");
add_line(path,"Joint Velocity/1","Joint Position/1");
add_line(path,"Joint Position/1","Dynamics/1","autorouting","on");
add_line(path,"Joint Velocity/1","Dynamics/2","autorouting","on");
add_line(path,"Joint Position/1","q/1");
add_line(path,"Joint Velocity/1","dq/1","autorouting","on");
end

function script = plantScript()
script = strjoin([ ...
    "function ddq = plant(q,dq,tau,p)"; ...
    "L1=p(1); L2=p(2); m1=p(3); m2=p(4); mp=p(5);"; ...
    "r1=p(6); r2=p(7); I1=p(8); I2=p(9); g=p(10); b=p(11:12);"; ...
    "coupling=m2*L1*r2+mp*L1*L2;"; ...
    "base=I1+I2+m1*r1^2+m2*(L1^2+r2^2)+mp*(L1^2+L2^2);"; ...
    "distal=I2+m2*r2^2+mp*L2^2;"; ...
    "M=[base+2*coupling*cos(q(2)),distal+coupling*cos(q(2));"; ...
    "   distal+coupling*cos(q(2)),distal];"; ...
    "C=[-coupling*sin(q(2))*dq(2),-coupling*sin(q(2))*(dq(1)+dq(2));"; ...
    "   coupling*sin(q(2))*dq(1),0];"; ...
    "distalGravity=(m2*r2+mp*L2)*g*cos(q(1)+q(2));"; ...
    "G=[(m1*r1+(m2+mp)*L1)*g*cos(q(1))+distalGravity;distalGravity];"; ...
    "ddq=M\(tau-C*dq-G-b.*dq);"; ...
    "end"], newline);
end

function buildLogging(path)
Simulink.SubSystem.deleteContents(path);
names = ["q","dq","tau","tauUnsaturated"];
for index = 1:numel(names)
    y = 40 + (index-1)*65;
    add_block("simulink/Ports & Subsystems/In1",path + "/" + names(index), ...
        "Port",string(index),"Position",[25 y 55 y+20]);
    add_block("simulink/Sinks/Terminator",path + "/End " + names(index), ...
        "Position",[150 y 170 y+20]);
    add_line(path,names(index) + "/1","End " + names(index) + "/1");
end
end

function connectTopLevel(modelName)
add_line(modelName,"Reference/1","PID Controller/1");
add_line(modelName,"Reference/2","PID Controller/2");
qLine = add_line(modelName,"Two-Link Plant/1","PID Controller/3", ...
    "autorouting","on");
add_line(modelName,"Two-Link Plant/1","Logging/1","autorouting","on");
dqLine = add_line(modelName,"Two-Link Plant/2","PID Controller/4", ...
    "autorouting","on");
add_line(modelName,"Two-Link Plant/2","Logging/2","autorouting","on");
tauLine = add_line(modelName,"PID Controller/1","Two-Link Plant/1", ...
    "autorouting","on");
add_line(modelName,"PID Controller/1","Logging/3","autorouting","on");
tauUnsaturatedLine = add_line(modelName,"PID Controller/2","Logging/4", ...
    "autorouting","on");
configureLoggedSignal(qLine,"q");
configureLoggedSignal(dqLine,"dq");
configureLoggedSignal(tauLine,"tau");
configureLoggedSignal(tauUnsaturatedLine,"tauUnsaturated");
end

function configureLoggedSignal(lineHandle, name)
set_param(lineHandle,"Name",name);
sourcePort = get_param(lineHandle,"SrcPortHandle");
set_param(sourcePort, ...
    "DataLogging","on", ...
    "DataLoggingNameMode","Custom", ...
    "DataLoggingName",name);
end

function assignDefaultParameters(modelName)
robot = rrm.config.makeRobot("baseline");
controller = rrm.config.makePidController(robot);
sampleTime = 0.001;
reference = rrm.trajectory.quintic([0;0],deg2rad([5;8]), ...
    0.02,sampleTime,0.03);
workspace = get_param(modelName,"ModelWorkspace");
assignin(workspace,"rrmSampleTime",sampleTime);
assignin(workspace,"rrmStopTime",reference.time(end));
assignin(workspace,"rrmQReferenceSignal", ...
    timeseries(reference.q.',reference.time));
assignin(workspace,"rrmDqReferenceSignal", ...
    timeseries(reference.dq.',reference.time));
assignin(workspace,"rrmKp",controller.Kp);
assignin(workspace,"rrmKi",controller.Ki);
assignin(workspace,"rrmKd",controller.Kd);
assignin(workspace,"rrmDerivativeAlpha", ...
    exp(-2*pi*controller.derivativeFilterHz*sampleTime));
assignin(workspace,"rrmAntiWindupGain",controller.antiWindupGain);
assignin(workspace,"rrmTorqueLimits", ...
    min(controller.torqueLimits,robot.torqueLimits));
assignin(workspace,"rrmInitialQ",reference.q(:,1));
assignin(workspace,"rrmInitialDq",zeros(2,1));
assignin(workspace,"rrmPlantParameters",[ ...
    robot.L1; robot.L2; robot.m1; robot.m2; robot.payload; ...
    robot.com; robot.inertia; robot.gravity; robot.viscousFriction]);
end

function addModelAnnotation(modelName)
annotation = Simulink.Annotation(modelName, ...
    "Phase 6A numerical cross-validation | q [rad], dq [rad/s], tau [N m]" + ...
    newline + "Plant equations are local to this model and execute with fixed-step ode4.");
annotation.Position = [300 315 760 355];
end

function closeIfLoaded(modelName)
if bdIsLoaded(modelName)
    close_system(modelName,0);
end
end
