function comparison = comparePidRuns(matlabRun,simulinkRun)
%COMPAREPIDRUNS Quantify numerical agreement between execution paths.
arguments
    matlabRun (1,1) struct
    simulinkRun (1,1) struct
end

[matlabTime,matlabData] = validateRun(matlabRun);
[simulinkTime,simulinkData] = validateRun(simulinkRun);
if ~isequal(size(matlabTime),size(simulinkTime)) || ...
        any(abs(matlabTime-simulinkTime) > ...
        100*eps(max(matlabTime(end),1)))
    error("rrm:simulink:TimeGridMismatch", ...
        "MATLAB and Simulink time grids must match exactly.");
end
sampleTime = matlabTime(2)-matlabTime(1);
if any(abs(diff(matlabTime)-sampleTime) > ...
        100*eps(max(matlabTime(end),1)))
    error("rrm:simulink:TimeGridMismatch", ...
        "Comparison requires a uniform time grid.");
end

qDifference = simulinkData.q-matlabData.q;
dqDifference = simulinkData.dq-matlabData.dq;
tauDifference = simulinkData.tau-matlabData.tau;
qRmsDifference = rmsByJoint(qDifference);
qMaxDifference = max(abs(qDifference),[],2);
dqRmsDifference = rmsByJoint(dqDifference);
dqMaxDifference = max(abs(dqDifference),[],2);
tauRmsDifference = rmsByJoint(tauDifference);
tauMaxDifference = max(abs(tauDifference),[],2);
matlabSaturationTime = sum(matlabData.saturated,2)*sampleTime;
simulinkSaturationTime = sum(simulinkData.saturated,2)*sampleTime;
saturationTimeDifference = abs( ...
    simulinkSaturationTime-matlabSaturationTime);

thresholds = struct( ...
    "qRms",1e-5, ...
    "qMax",5e-5, ...
    "dqRms",1e-4, ...
    "tauRms",5e-3, ...
    "saturationTime",sampleTime);
flags = struct( ...
    "qRms",qRmsDifference <= thresholds.qRms, ...
    "qMax",qMaxDifference <= thresholds.qMax, ...
    "dqRms",dqRmsDifference <= thresholds.dqRms, ...
    "tauRms",tauRmsDifference <= thresholds.tauRms, ...
    "saturationTime",saturationTimeDifference <= ...
        thresholds.saturationTime + 10*eps(sampleTime), ...
    "completed",matlabRun.status == "completed" && ...
        simulinkRun.status == "completed" && ...
        matlabRun.completedSamples == numel(matlabTime) && ...
        simulinkRun.completedSamples == numel(simulinkTime));

failureSummary = summarizeFailures(flags);
comparison = struct( ...
    "sampleTime",sampleTime, ...
    "thresholds",thresholds, ...
    "qDifference",qDifference, ...
    "dqDifference",dqDifference, ...
    "tauDifference",tauDifference, ...
    "qRmsDifference",qRmsDifference, ...
    "qMaxDifference",qMaxDifference, ...
    "dqRmsDifference",dqRmsDifference, ...
    "dqMaxDifference",dqMaxDifference, ...
    "tauRmsDifference",tauRmsDifference, ...
    "tauMaxDifference",tauMaxDifference, ...
    "matlabSaturationTime",matlabSaturationTime, ...
    "simulinkSaturationTime",simulinkSaturationTime, ...
    "saturationTimeDifference",saturationTimeDifference, ...
    "flags",flags, ...
    "pass",strlength(failureSummary) == 0, ...
    "failureSummary",failureSummary);
end

function [time,data] = validateRun(run)
required = ["time","q","dq","tau","saturated","status", ...
    "completedSamples"];
if ~all(isfield(run,required))
    error("rrm:simulink:InvalidComparisonData", ...
        "Each run must define aligned state, torque, and status fields.");
end
time = run.time;
sampleCount = numel(time);
isValidShape = isequal(size(time),[sampleCount 1]) && sampleCount >= 2 && ...
    isequal(size(run.q),[2 sampleCount]) && ...
    isequal(size(run.dq),[2 sampleCount]) && ...
    isequal(size(run.tau),[2 sampleCount]) && ...
    isequal(size(run.saturated),[2 sampleCount]);
if ~isValidShape || ~isstring(run.status) || ~isscalar(run.status) || ...
        ~isscalar(run.completedSamples) || ...
        ~isfinite(run.completedSamples)
    error("rrm:simulink:InvalidComparisonData", ...
        "Run histories and status fields have invalid dimensions or types.");
end
if any(~isfinite([time.';run.q;run.dq;run.tau]),"all") || ...
        any(~isfinite(double(run.saturated)),"all")
    error("rrm:simulink:NonFiniteComparisonData", ...
        "Comparison histories must contain finite data only.");
end
if any(diff(time) <= 0)
    error("rrm:simulink:TimeGridMismatch", ...
        "Comparison time must be strictly increasing.");
end
data = struct( ...
    "q",run.q, ...
    "dq",run.dq, ...
    "tau",run.tau, ...
    "saturated",logical(run.saturated));
end

function value = rmsByJoint(history)
value = sqrt(mean(history.^2,2));
end

function summary = summarizeFailures(flags)
failures = strings(0,1);
labels = ["q-rms","q-max","dq-rms","tau-rms","saturation-time"];
values = {flags.qRms,flags.qMax,flags.dqRms, ...
    flags.tauRms,flags.saturationTime};
for metric = 1:numel(labels)
    for joint = 1:2
        if ~values{metric}(joint)
            failures(end+1,1) = labels(metric) + "-j" + joint; %#ok<AGROW>
        end
    end
end
if ~flags.completed
    failures(end+1,1) = "completed";
end
summary = strjoin(failures,", ");
end
