function result = runPidCrossValidation( ...
        robot, controller, reference, options, modelPath)
%RUNPIDCROSSVALIDATION Run the fixed-gain PID in the validation model.
arguments
    robot (1,1) struct
    controller (1,1) struct
    reference (1,1) struct
    options (1,1) struct
    modelPath (1,1) string
end

validateController(controller);
sampleTime = validateReference(reference,options);
validateEnvironment(options,reference);
modelPath = resolveModelPath(modelPath);
if ~isfile(modelPath)
    rrm.simulink.buildPidCrossValidationModel(modelPath);
end
[~,modelName] = fileparts(modelPath);
load_system(modelPath);
cleanup = onCleanup(@() closeIfLoaded(modelName));

simulationInput = Simulink.SimulationInput(modelName);
simulationInput = setModelParameter(simulationInput, ...
    "StopTime",string(reference.time(end)), ...
    "FixedStep",string(sampleTime));
simulationInput = setModelVariable(simulationInput,modelName, ...
    "rrmSampleTime",sampleTime);
simulationInput = setModelVariable(simulationInput,modelName, ...
    "rrmStopTime",reference.time(end));
simulationInput = setModelVariable(simulationInput,modelName, ...
    "rrmQReferenceSignal",timeseries(reference.q.',reference.time));
simulationInput = setModelVariable(simulationInput,modelName, ...
    "rrmDqReferenceSignal",timeseries(reference.dq.',reference.time));
simulationInput = setModelVariable(simulationInput,modelName,"rrmKp",controller.Kp);
simulationInput = setModelVariable(simulationInput,modelName,"rrmKi",controller.Ki);
simulationInput = setModelVariable(simulationInput,modelName,"rrmKd",controller.Kd);
simulationInput = setModelVariable(simulationInput,modelName, ...
    "rrmDerivativeAlpha", ...
    exp(-2*pi*controller.derivativeFilterHz*sampleTime));
simulationInput = setModelVariable(simulationInput,modelName, ...
    "rrmAntiWindupGain",controller.antiWindupGain);
torqueLimits = min(controller.torqueLimits,robot.torqueLimits);
simulationInput = setModelVariable(simulationInput,modelName, ...
    "rrmTorqueLimits",torqueLimits);
simulationInput = setModelVariable(simulationInput,modelName, ...
    "rrmInitialQ",reference.q(:,1));
simulationInput = setModelVariable(simulationInput,modelName, ...
    "rrmInitialDq",options.initialVelocity);
simulationInput = setModelVariable(simulationInput,modelName, ...
    "rrmPlantParameters",plantParameters(robot));

toolchainWarning = "coder_compile:toolchain:DefaultToolchainNotInRegistry";
warningState = warning("query",toolchainWarning);
warning("off",toolchainWarning);
warningCleanup = onCleanup(@() warning(warningState));
simulationOutput = sim(simulationInput);
clear warningCleanup
logs = simulationOutput.logsout;
[time,q] = readLoggedSignal(logs,"q");
[dqTime,dq] = readLoggedSignal(logs,"dq");
[tauTime,tau] = readLoggedSignal(logs,"tau");
[unsaturatedTime,tauUnsaturated] = readLoggedSignal( ...
    logs,"tauUnsaturated");
validateOutputGrids(reference.time,time,dqTime,tauTime,unsaturatedTime);
if any(~isfinite([q;dq;tau;tauUnsaturated]),"all")
    error("rrm:simulink:NonFiniteOutput", ...
        "Simulink returned one or more non-finite output samples.");
end
saturated = abs(tauUnsaturated-tau) > ...
    100*eps(max(abs(tau),1));

result = struct( ...
    "time",time, ...
    "q",q, ...
    "dq",dq, ...
    "qReference",reference.q, ...
    "dqReference",reference.dq, ...
    "tau",tau, ...
    "tauUnsaturated",tauUnsaturated, ...
    "saturated",saturated, ...
    "status","completed", ...
    "completedSamples",numel(time));
clear cleanup
end

function simulationInput = setModelVariable( ...
        simulationInput,modelName,name,value)
simulationInput = setVariable(simulationInput,name,value, ...
    Workspace=modelName);
end

function parameters = plantParameters(robot)
required = ["L1","L2","m1","m2","payload","com","inertia", ...
    "gravity","viscousFriction","torqueLimits"];
if ~all(isfield(robot,required))
    error("rrm:simulink:InvalidRobot", ...
        "Robot is missing required physical parameters.");
end
parameters = [robot.L1;robot.L2;robot.m1;robot.m2;robot.payload; ...
    robot.com;robot.inertia;robot.gravity;robot.viscousFriction];
if ~isequal(size(parameters),[12 1]) || ...
        any(~isfinite(parameters)) || any(parameters(1:4) <= 0) || ...
        parameters(5) < 0 || parameters(10) <= 0
    error("rrm:simulink:InvalidRobot", ...
        "Robot physical parameters are invalid.");
end
end

function validateController(controller)
required = ["type","Kp","Ki","Kd","derivativeFilterHz", ...
    "antiWindupGain","torqueLimits"];
if ~all(isfield(controller,required)) || controller.type ~= "pid"
    error("rrm:simulink:UnsupportedController", ...
        "Phase 6A supports fixed-gain PID controllers only.");
end
vectors = {controller.Kp,controller.Ki,controller.Kd, ...
    controller.antiWindupGain,controller.torqueLimits};
if any(cellfun(@(value) ~isequal(size(value),[2 1]) || ...
        ~isreal(value) || any(~isfinite(value)) || any(value < 0),vectors)) || ...
        ~isscalar(controller.derivativeFilterHz) || ...
        ~isfinite(controller.derivativeFilterHz) || ...
        controller.derivativeFilterHz <= 0
    error("rrm:simulink:UnsupportedController", ...
        "Fixed-gain PID parameters must be finite and nonnegative.");
end
end

function sampleTime = validateReference(reference,options)
requiredReference = ["time","q","dq","ddq"];
if ~all(isfield(reference,requiredReference)) || ...
        ~isfield(options,"sampleTime") || ...
        ~isfield(options,"initialVelocity")
    error("rrm:simulink:InvalidReference", ...
        "Reference or simulation options are incomplete.");
end
sampleTime = options.sampleTime;
sampleCount = numel(reference.time);
isValidArrays = isequal(size(reference.time),[sampleCount 1]) && ...
    isequal(size(reference.q),[2 sampleCount]) && ...
    isequal(size(reference.dq),[2 sampleCount]) && ...
    isequal(size(reference.ddq),[2 sampleCount]) && ...
    all(isfinite([reference.time.';reference.q;reference.dq;reference.ddq]),"all");
isValidStep = isscalar(sampleTime) && isfinite(sampleTime) && ...
    sampleTime > 0 && sampleTime == 0.001 && ...
    all(abs(diff(reference.time)-sampleTime) <= ...
    100*eps(max(reference.time(end),1)));
if ~isValidArrays || sampleCount < 2 || ~isValidStep || ...
        ~isequal(size(options.initialVelocity),[2 1]) || ...
        any(~isfinite(options.initialVelocity))
    error("rrm:simulink:InvalidReference", ...
        "Reference must use finite aligned arrays on the 1 ms grid.");
end
end

function validateEnvironment(options,reference)
sampleCount = numel(reference.time);
if ~isfield(options,"disturbanceTorque") || ...
        ~isZeroHistory(options.disturbanceTorque,sampleCount)
    error("rrm:simulink:UnsupportedEnvironment", ...
        "Phase 6A requires zero disturbance torque.");
end
if isfield(options,"measurementNoise")
    noise = options.measurementNoise;
    if ~isstruct(noise) || ~all(isfield(noise,["position","velocity"])) || ...
            ~isZeroHistory(noise.position,sampleCount) || ...
            ~isZeroHistory(noise.velocity,sampleCount)
        error("rrm:simulink:UnsupportedEnvironment", ...
            "Phase 6A requires zero measurement noise.");
    end
end
end

function valid = isZeroHistory(value,sampleCount)
valid = isnumeric(value) && isreal(value) && ...
    (isequal(size(value),[2 1]) || isequal(size(value),[2 sampleCount])) && ...
    all(isfinite(value),"all") && all(value == 0,"all");
end

function modelPath = resolveModelPath(modelPath)
if ~java.io.File(char(modelPath)).isAbsolute()
    functionPath = mfilename("fullpath");
    projectRoot = fileparts(fileparts(fileparts(functionPath)));
    modelPath = fullfile(projectRoot,modelPath);
end
[~,name,extension] = fileparts(modelPath);
if ~strcmpi(extension,".slx") || strlength(name) == 0 || ~isvarname(name)
    error("rrm:simulink:InvalidModelPath", ...
        "Model path must name a valid .slx file.");
end
modelPath = string(java.io.File(char(modelPath)).getCanonicalPath());
end

function [time,data] = readLoggedSignal(logs,name)
element = logs.get(name);
if isempty(element)
    error("rrm:simulink:MissingLoggedSignal", ...
        "Logged signal '%s' is missing.",name);
end
values = element.Values;
time = values.Time;
data = squeeze(values.Data);
if size(data,1) == numel(time)
    data = data.';
end
if ~isequal(size(data),[2 numel(time)])
    error("rrm:simulink:MissingLoggedSignal", ...
        "Logged signal '%s' must be a two-element vector history.",name);
end
end

function validateOutputGrids(referenceTime,varargin)
for grid = varargin
    time = grid{1};
    if ~isequal(size(time),size(referenceTime)) || ...
            any(abs(time-referenceTime) > ...
            100*eps(max(referenceTime(end),1)))
        error("rrm:simulink:TimeGridMismatch", ...
            "Simulink output time grid does not match the reference.");
    end
end
end

function closeIfLoaded(modelName)
if bdIsLoaded(modelName)
    close_system(modelName,0);
end
end
